(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib._05_1 = function() {
	this.initialize(img._05_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,322,52);


(lib._300x250_paint_group_lineup = function() {
	this.initialize(img._300x250_paint_group_lineup);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1053,336);


(lib.Cabot_LG = function() {
	this.initialize(img.Cabot_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,156,191);


(lib.Krylon_LG = function() {
	this.initialize(img.Krylon_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,81,221);


(lib.lowes_blue_solid = function() {
	this.initialize(img.lowes_blue_solid);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,272,69);


(lib.lowes_blue_solidpngcopy = function() {
	this.initialize(img.lowes_blue_solidpngcopy);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,272,69);


(lib.Minwax_LG = function() {
	this.initialize(img.Minwax_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,164,189);


(lib.Purdy_LG = function() {
	this.initialize(img.Purdy_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,81,280);


(lib.Sherwin_LG = function() {
	this.initialize(img.Sherwin_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,171,216);


(lib.Thompsons_LG = function() {
	this.initialize(img.Thompsons_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,186,283);


(lib.Valspar_LG = function() {
	this.initialize(img.Valspar_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,194,238);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.valspar_dura = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Valspar_LG();
	this.instance.parent = this;
	this.instance.setTransform(4,9,0.302,0.302);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4,9,58.6,71.9);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.lowes_blue_solid();
	this.instance.parent = this;
	this.instance.setTransform(-439,-14,0.279,0.28);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-439,-14,76,19.3);


(lib.thopson_waterseal = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Thompsons_LG();
	this.instance.parent = this;
	this.instance.setTransform(2,-1,0.287,0.287);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2,-1,53.3,81.1);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.lowes_blue_solidpngcopy();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.581,0.581);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,158,40.1), null);


(lib.sherwin_infinity = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Sherwin_LG();
	this.instance.parent = this;
	this.instance.setTransform(-1,11,0.362,0.362);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,11,62,78.3);


(lib.purdy_brush = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Purdy_LG();
	this.instance.parent = this;
	this.instance.setTransform(-10,13,0.416,0.416);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10,13,33.7,116.5);


(lib.paint_lineup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib._300x250_paint_group_lineup();
	this.instance.parent = this;
	this.instance.setTransform(383,-103,0.055,0.055);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(383,-103,58,18.5);


(lib.minwax_wood = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Minwax_LG();
	this.instance.parent = this;
	this.instance.setTransform(1,12,0.308,0.31);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1,12,50.6,58.6);


(lib.krylon_fusion = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Krylon_LG();
	this.instance.parent = this;
	this.instance.setTransform(5,13,0.352,0.352);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(5,13,28.6,77.9);


(lib.FR1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#004990").s().p("AgHAJQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAgPIABgBIAPAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAPQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAg");
	this.shape.setTransform(172.3,-41.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#004990").s().p("AgJAtIgKgDIgIgEIgGgEQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAAAABgBIAKgLQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAQAEADAGADQAGADAGAAQAHAAADgDQAEgDAAgFQAAgDgDgDQgDgCgHgBIgEgBQgOgCgHgGQgHgGAAgMQAAgGACgFQACgFAEgDQAEgEAGgCQAGgCAGAAQAJAAAIADQAIACAFAFQAAAAABAAQAAAAAAABQAAAAAAAAQgBAAAAABIgHALIgCABQgFgEgFgBQgFgCgGAAQgFAAgDADQgDADAAAEQAAADADADQAEACAGABIAFABQAOACAHAGQAHAGAAAMQAAAGgDAFQgCAFgEAEQgEAEgHACQgGACgJAAIgJgBg");
	this.shape_1.setTransform(166.7,-45.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#004990").s().p("AgfAsQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAgAAQAMAAAHAFQAIAFADAKIABAEIABAEIAAAHIAAAIIAAAJIAAAHIgBAFIgBADQgDAKgIAFQgHAFgMAAgAgNgZIAAAzIAAABIAKAAQAGAAAEgCQAEgCABgGIABgCIABgDIAAgFIAAgHIAAgGIAAgFIgBgDIgBgCQgBgGgEgCQgEgCgGAAIgKAAIAAABg");
	this.shape_2.setTransform(159,-45.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#004990").s().p("AASAsQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAIgeg3IAAAAIAAA3QAAAAgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgPAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAfA3IAAAAIAAg3QAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAPAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABVQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_3.setTransform(150.5,-45.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#004990").s().p("AAWAsIgBgBIgFgQIgeAAIgFAQQgBAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgRAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAehVQAAAAAAAAQABgBAAAAQAAAAAAAAQABAAAAAAIAQAAIABABIAeBVQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAgAAKALIgKgeIAAAAIgJAeIATAAg");
	this.shape_4.setTransform(142.1,-45.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#004990").s().p("AAPAsQAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAAAIgOggIgMAAIgBAAIAAAgQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgRAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAiAAQAHAAAGACQAGACAEAEQADADACAFQACAFABAGQgBAJgEAGQgEAGgHADIARAjIAAABIAAAAgAgOgaIAAAVIABAAIAOAAQAGAAADgDQADgDAAgFQAAgFgDgDQgDgDgGAAIgOAAIgBABg");
	this.shape_5.setTransform(134.1,-45.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#004990").s().p("AgeAsQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAhAAQAOAAAHAGQAHAHAAAKQAAAIgDAEQgDAFgEACIAEACIAEAEIADAGIABAHQAAAOgIAGQgJAGgOAAgAgNAHIAAAVIABABIAOAAQAGAAADgDQADgDAAgFQAAgFgDgDQgDgDgGAAIgOAAIgBAAgAgNgbIAAATIABABIANAAQAFAAADgDQADgCAAgFQAAgFgDgDQgDgDgFAAIgNAAIgBABg");
	this.shape_6.setTransform(126,-45.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#004990").s().p("AgHAsQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAhEIgBgBIgXAAQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgPQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIBBAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAPIgBABIgWAAIgBABIAABEQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAg");
	this.shape_7.setTransform(115.4,-45.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#004990").s().p("AgJAtIgKgDIgIgEIgGgEQAAAAgBgBQAAAAAAAAQAAgBAAAAQABAAAAgBIAKgLQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAQAEADAGADQAGADAGAAQAHAAADgDQAEgDAAgFQAAgDgDgDQgDgCgHgBIgEgBQgOgCgHgGQgHgGAAgMQAAgGACgFQACgFAEgDQAEgEAGgCQAGgCAGAAQAJAAAIADQAIACAFAFQAAAAABAAQAAAAAAABQAAAAAAAAQgBAAAAABIgHALIgCABQgFgEgFgBQgFgCgGAAQgFAAgDADQgDADAAAEQAAADADADQAEACAGABIAFABQAOACAHAGQAHAGAAAMQAAAGgDAFQgCAFgEAEQgEAEgHACQgGACgJAAIgJgBg");
	this.shape_8.setTransform(108.1,-45.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#004990").s().p("AgbAsQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIA3AAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAOIgBABIgkAAIgBABIAAASIABABIAeAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAANQAAAAgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgeAAIgBABIAAASIABABIAkAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAOQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAg");
	this.shape_9.setTransform(100.8,-45.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#004990").s().p("AgeAsQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAhAAQAOAAAHAGQAHAHAAAKQAAAIgDAEQgDAFgEACIAEACIAEAEIADAGIABAHQAAAOgIAGQgJAGgOAAgAgNAHIAAAVIABABIAOAAQAGAAADgDQADgDAAgFQAAgFgDgDQgDgDgGAAIgOAAIgBAAgAgNgbIAAATIABABIANAAQAFAAADgDQADgCAAgFQAAgFgDgDQgDgDgFAAIgNAAIgBABg");
	this.shape_10.setTransform(93.2,-45.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#004990").s().p("AgbAsQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIA3AAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAOIgBABIglAAIgBABIAAASIABABIAfAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAANQAAAAgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgfAAIgBABIAAASIABABIAlAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAOQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAg");
	this.shape_11.setTransform(82.5,-45.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#004990").s().p("AARAsQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgiIgBgBIgbAAIgBABIAAAiQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAIgRAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIARAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAhIABABIAbAAIABgBIAAghQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAQAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAABVQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAg");
	this.shape_12.setTransform(74.4,-45.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#004990").s().p("AgHAsQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAhEIgBgBIgXAAQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgPQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIBBAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAPIgBABIgXAAIAAABIAABEQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAg");
	this.shape_13.setTransform(66.6,-45.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#004990").s().p("AgbAsQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIA3AAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAOIgBABIgkAAIgBABIAAATIABABIAeAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAANQAAAAAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgeAAIgBABIAAAhQAAAAgBAAQAAABAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_14.setTransform(148.4,-59.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#004990").s().p("AgTAoQgJgFgDgLIgBgEIgBgFIgBgGIAAgJIAAgHIABgHIABgFIABgEQADgLAJgFQAJgGAKAAQAMAAAIAGQAJAFADALIACAEIAAAFIABAHIAAAHIAAAJIgBAGIAAAFIgCAEQgDALgJAFQgIAGgMAAQgKAAgJgGgAgIgZQgDADgCAEIAAADIgBADIAAAGIAAAGIAAAHIAAAGIABADIAAADQACAFADACQAEADAEAAQAGAAADgDQAEgCABgFIABgDIAAgDIAAgGIAAgHIAAgGIAAgGIAAgDIgBgDQgBgEgEgDQgDgDgGAAQgEAAgEADg");
	this.shape_15.setTransform(140.5,-59.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#004990").s().p("AgfAsQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAhAAQAHAAAGACQAGACAEAEQAEAEACAFQACAFAAAGQAAAHgCAFQgCAEgEAEQgEAEgGACQgGACgHAAIgOAAIgBAAIAAAeQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAgAgNgaIAAAWIABABIANAAQAGAAAEgDQADgDAAgGQAAgFgDgDQgEgEgGAAIgNAAIgBABg");
	this.shape_16.setTransform(129.7,-59.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#004990").s().p("AgNArQgGgCgFgFQgEgEgDgHQgCgGAAgIIAAg2QAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIARAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAA2QAAAJAEAEQAEAEAGAAQAHAAAEgEQADgEAAgJIAAg2QAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAQAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAA2QAAAIgDAGQgDAHgEAEQgEAFgHACQgFACgIAAQgGAAgHgCg");
	this.shape_17.setTransform(121.4,-59.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#004990").s().p("AgbAsQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAgBAAIAAhVQABAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIA3AAQABAAAAAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAAOIgCABIglAAIgBABIAAASIABABIAfAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAANQAAAAgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgfAAIgBABIAAASIABABIAlAAQABAAAAAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAAOQAAAAgBAAQAAABAAAAQAAAAAAAAQAAAAgBAAg");
	this.shape_18.setTransform(113.7,-59.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#004990").s().p("AASAsQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAIgeg3IgBAAIAAA3QAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgPAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAfA3IAAAAIAAg3QAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAPAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABVQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_19.setTransform(105.6,-59.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#004990").s().p("AgHAsQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAQAAQAAAAAAAAQAAAAAAAAQAAAAAAABQABAAAAAAIAABVQAAAAgBAAQAAABAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_20.setTransform(99.6,-59.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#004990").s().p("AgbAsQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAQAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABEIABABIAmAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAOQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_21.setTransform(94.5,-59.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#004990").s().p("AAPAsQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgPggIgLAAIgBAAIAAAgQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgQAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAiAAQAGAAAGACQAFACAEAEQAEADADAFQABAFAAAGQAAAJgDAGQgFAGgHADIARAjIAAABIgBAAgAgOgaIAAAVIABAAIAPAAQAFAAADgDQADgDAAgFQAAgFgDgDQgDgDgFAAIgPAAIgBABg");
	this.shape_22.setTransform(83.7,-59.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#004990").s().p("AgMArQgHgCgFgFQgEgEgCgHQgDgGAAgIIAAg2QAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAQAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAA2QAAAJAEAEQAEAEAGAAQAGAAAEgEQAFgEAAgJIAAg2QAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIARAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAA2QAAAIgCAGQgEAHgEAEQgEAFgGACQgHACgHAAQgHAAgFgCg");
	this.shape_23.setTransform(75.3,-59.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#004990").s().p("AgTAoQgJgFgDgLIgBgEIgBgFIgBgGIAAgJIAAgHIABgHIABgFIABgEQADgLAJgFQAJgGAKAAQAMAAAIAGQAJAFADALIACAEIAAAFIABAHIAAAHIAAAJIgBAGIAAAFIgCAEQgDALgJAFQgIAGgMAAQgKAAgJgGgAgIgZQgDADgCAEIAAADIgBADIAAAGIAAAGIAAAHIAAAGIABADIAAADQACAFADACQAEADAEAAQAGAAADgDQAEgCABgFIABgDIAAgDIAAgGIAAgHIAAgGIAAgGIAAgDIgBgDQgBgEgEgDQgDgDgGAAQgEAAgEADg");
	this.shape_24.setTransform(67,-59.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#004990").s().p("AgTAoQgJgFgDgLIgBgEIgBgFIgBgGIAAgJIAAgHIABgHIABgFIABgEQADgLAJgFQAJgGAKAAQAHAAAFACIAJAEQAEACACAEQADADACAEQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgOAGQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQgDgEgEgCQgDgDgGAAQgEAAgEADQgDADgCAEIAAADIgBAEIAAAFIAAAGIAAAHIAAAGIABADIAAADQACAFADACQAEADAFAAQAFAAADgDQAEgCACgEIABgEIAAgFIgBgBIgMAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgMQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAeAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAHIgBALIgBAJQgEAKgIAGQgJAGgMAAQgKAAgJgGg");
	this.shape_25.setTransform(138.6,-74.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#004990").s().p("AASAsQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAIgeg3IAAAAIAAA3QAAAAgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgPAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAfA3IAAAAIAAg3QAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAPAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABVQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_26.setTransform(130.3,-74.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#004990").s().p("AgHAsQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAhVQAAAAABAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAPAAQABAAAAAAQAAAAAAAAQAAAAAAABQABAAAAAAIAABVQAAAAgBAAQAAABAAAAQAAAAAAAAQAAAAgBAAg");
	this.shape_27.setTransform(124.2,-74.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#004990").s().p("AgSAoQgIgFgDgLIgBgEIgBgFIgBgGIAAgJIAAgIIABgGIABgFIABgEQADgLAIgFQAJgGAKAAQAMAAAHAGQAIAFAEAJQABAAAAABQAAAAgBAAQAAAAAAAAQAAABgBAAIgOAGQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAgBgBQgBgEgEgDQgDgDgGAAQgEAAgDADQgDADgCAEIAAADIgBADIAAAFIAAAHIAAAIIAAAFIABAEIAAACQACAFADACQADADAEAAQAGAAADgDQAEgDABgEQABgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAIAOAHQABAAAAAAQAAAAAAAAQABAAAAABQAAAAgBAAQgEAJgIAGQgHAFgMAAQgKAAgJgGg");
	this.shape_28.setTransform(118.8,-74.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#004990").s().p("AgNArQgGgCgEgFQgFgEgDgGQgCgHAAgIIAAg2QAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIARAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAA2QAAAJAEAEQAEAEAGAAQAGAAAFgEQADgEAAgJIAAg2QAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAQAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAA2QAAAIgDAHQgDAGgEAEQgEAFgHACQgFACgIAAQgGAAgHgCg");
	this.shape_29.setTransform(110.8,-74.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#004990").s().p("AgfAsQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAhVQAAAAABAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAfAAQAMAAAIAFQAIAFADAKIABAEIABAEIABAHIAAAIIAAAJIgBAHIgBAFIgBADQgDAKgIAFQgIAFgMAAgAgOgZIAAAzIACABIAKAAQAFAAAEgCQAEgCABgGIACgCIAAgDIAAgFIAAgHIAAgGIAAgFIAAgDIgCgCQgBgGgEgCQgEgCgFAAIgKAAIgCABg");
	this.shape_30.setTransform(102.7,-74.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#004990").s().p("AgTAoQgJgFgDgLIgBgEIgBgFIgBgGIAAgJIAAgHIABgHIABgFIABgEQADgLAJgFQAJgGAKAAQAMAAAIAGQAJAFADALIACAEIAAAFIABAHIAAAHIAAAJIgBAGIAAAFIgCAEQgDALgJAFQgIAGgMAAQgKAAgJgGgAgIgZQgDADgCAEIAAADIgBADIAAAGIAAAGIAAAHIAAAGIABADIAAADQACAFADACQAEADAEAAQAGAAADgDQAEgCABgFIABgDIAAgDIAAgGIAAgHIAAgGIAAgGIAAgDIgBgDQgBgEgEgDQgDgDgGAAQgEAAgEADg");
	this.shape_31.setTransform(94.4,-74.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#004990").s().p("AAPAsQAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAAAIgPggIgLAAIgBAAIAAAgQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgRAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAjAAQAGAAAGACQAFACAEAEQAEADACAFQACAFAAAGQAAAJgDAGQgFAGgHADIARAjIAAABIgBAAgAgOgaIAAAVIABAAIAPAAQAFAAADgDQADgDAAgFQAAgFgDgDQgDgDgFAAIgPAAIgBABg");
	this.shape_32.setTransform(86.5,-74.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#004990").s().p("AgHAsQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAhEIAAgBIgWAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAAAIAAgPQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIBAAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAPIgBABIgWAAIgBABIAABEQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_33.setTransform(78.7,-74.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#004990").s().p("AARAsQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAIgeg3IgBAAIAAA3QAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgOAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAPAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAeA3IABAAIAAg3QAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAPAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABVQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_34.setTransform(70.8,-74.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#004990").s().p("AgHAsQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAQAAQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAABVQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_35.setTransform(64.8,-74.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.FR1copy, new cjs.Rectangle(61,-83,176.6,48.8), null);


(lib.Disclaimer = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AgBADIAAgBIAAgDIAAgBIADAAIABABIAAADIgBABg");
	this.shape.setTransform(312.1,-514.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AgGARIgBgBIAAgDIABgBIAAAAIADAAIACgDIAAgCIgJgWIABgBIADAAIABABIAFAQIAGgQIABgBIADAAQABABAAAAIgKAYIgBAEIgBACIgCABIgCABg");
	this.shape_1.setTransform(310.6,-515.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AADARIgBAAQgBAAgBAAQAAAAAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAgBQAAAAAAgBIAAgaIAAgBIADAAIAAABIAAAaIABACIABABIABAAIABAAIAAADg");
	this.shape_2.setTransform(308.9,-516.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AAGAMIgBAAIAAgNIgBgFQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAABIAAANIgBAAIgDAAIgBAAIAAgWIABgBIADAAIABABIAAACIACgCIADgBQAEAAACACQADADAAAEIAAAOIgBAAg");
	this.shape_3.setTransform(306.8,-515.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQADACABADIAAADIAAACIAAADIAAADQgBADgDACQgCABgEAAQgCAAgDgBgAgCgHIgCADIgBACIAAACIAAADIABACIACADIACABIAEgBIACgDIAAgCIAAgDIAAgCIAAgCIgCgDIgEgBIgCABg");
	this.shape_4.setTransform(304.1,-515.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AgBADIAAgBIAAgDIAAgBIADAAIAAABIAAADIAAABg");
	this.shape_5.setTransform(301.2,-514.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AgDARIgDgBIgDgBIgCgBIAAgBIACgDIABAAIAEADIAEABQAEgBACgBQAAgBABAAQAAgBAAAAQABgBAAAAQAAgBAAgBIgBgCIgBgBIgCgBIgDgBIgBAAQgKgCAAgGIABgFIACgDIADgCIAEgBIAGACIAEACIAAABIgBACIgBAAIgEgCIgEAAQgCgBgCACQAAAAgBABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQABAAAAABQAAAAAAABQABAAAAABQACABADAAIABABQAFABADABQACACAAAEIgBAFIgCACIgEADIgFAAIgDAAg");
	this.shape_6.setTransform(299.1,-516.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AgBADIgBgBIAAgDIABgBIADAAIABABIAAADIgBABg");
	this.shape_7.setTransform(297.1,-514.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AgIAOQgDgDAAgGIAAgVIABAAIADAAIAAAAIAAAVQAAAEACACQACACADAAQAEAAABgCQADgCAAgEIAAgVIAAAAIADAAIABAAIAAAVQAAAGgDADQgDADgGAAQgEAAgEgDg");
	this.shape_8.setTransform(295.1,-516.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#333333").s().p("AgBAOIAAgKIABAAIACAAIAAAAIAAAFIAAABIAAAAIgCAEIAAABIgBgBgAgBgIIAAgBIAAgEIAAgBIADAAIAAABIAAAEIAAABg");
	this.shape_9.setTransform(291.7,-515.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#333333").s().p("AgCAMIgDgBIgCgBIgCgBIAAgBIACgCIABAAIADACIADABIAEgBQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAIgBgCIgEgBIgCgBQgDAAgCgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgDADgCQACgCADAAIAFAAIAEACIAAABIgCACIgBAAIgDgBIgDgBIgDABIgBACIABADIADABIADAAQADAAACABQAAAAABABQAAABAAAAQABABAAAAQAAABAAAAQAAAEgDACQgCACgFAAIgCAAg");
	this.shape_10.setTransform(289.8,-515.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("AgFAQIgDgEIgBgDIAAgEIAAgEIABgCQABgDACgBQACgCADAAIADABIADADIAAgNIAAAAIAEAAIAAAAIAAAgIAAABIgEAAIAAgBIAAgCIgDACIgDABQgDAAgCgBgAgEAAIgBACIAAADIAAADIABACQABADADAAQAEAAABgDIABgCIAAgDIAAgDIgBgCQgBgDgEAAQgDAAgBADg");
	this.shape_11.setTransform(287.2,-516.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#333333").s().p("AAGAMIgBAAIAAgNIgBgFQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQgBAAAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAABIAAANIgBAAIgDAAIgBAAIAAgWIABgBIADAAIABABIAAACIACgCIADgBQAEAAACACQADADAAAEIAAAOIgBAAg");
	this.shape_12.setTransform(284.6,-515.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("AgDAMIgEgBIgBgCIgBgDQABgFACgBQACgBAEAAIAFAAIABAAIAAgCIgBgEQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgCAAIgDACIAAAAIgCgCIAAgBIAEgCIADAAQAFAAACACQACABAAAEIAAAPIAAABIgDAAIAAgBIAAgCIgDACIgEABIgCAAgAgDACQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAIADABQAAAAABAAQABAAAAAAQABgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAgBQABAAAAgBIAAgDIgBAAIgFAAIgDABg");
	this.shape_13.setTransform(282,-515.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#333333").s().p("AgGAMIgBAAIAAgWIABgBIADAAIABABIAAACIACgCIADgBIADAAIACACIAAAAIgCADIgBAAIgBgBIgCAAQgBAAgBAAQAAAAAAAAQAAAAgBABQAAAAAAABIgBAFIAAAMIgBAAg");
	this.shape_14.setTransform(280,-515.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("AgCAQIgCgCIAAACIgBABIgEAAIAAgBIAAggIAAAAIAEAAIABAAIAAANIACgDIADgBQADAAACACQACABABADIABACIAAAEIAAAEIgBADIgDAEQgCABgDAAIgDgBgAgEAAIAAACIAAADIAAADIAAACQABADADAAQAEAAACgDIAAgCIAAgDIAAgDIAAgCQgCgDgEAAQgDAAgBADg");
	this.shape_15.setTransform(277.6,-516.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQACACABADIABABIAAACIAAACIAAABIAAAAIgOAAIgBAAIAAACIABABIACAEIADABIADgBIADgCIABAAIACACIAAABIgEACIgGABQgCAAgDgBgAgCgHIgCADIgBADIABAAIAKAAIAAAAIAAgDIgCgDIgEgBIgCABg");
	this.shape_16.setTransform(273.7,-515.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AgCAMIgDgBIgCgBIgCgBIAAgBIACgCIABAAIADACIADABIAEgBQABAAAAgBQAAAAAAAAQABgBAAAAQAAgBAAAAIgBgCIgEgBIgCgBQgDAAgCgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAgDADgCQACgCADAAIAFAAIAEACIAAABIgCACIgBAAIgDgBIgDgBIgDABIgBACIABADIADABIADAAQADAAACABQAAAAABABQAAABAAAAQABABAAAAQAAABAAAAQAAAEgDACQgCACgFAAIgCAAg");
	this.shape_17.setTransform(271.2,-515.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQACACABADIABABIAAACIAAACIAAABIAAAAIgOAAIgBAAIAAACIABABIACAEIADABIADgBIADgCIABAAIACACIAAABIgEACIgGABQgCAAgDgBgAgCgHIgCADIgBADIABAAIAKAAIAAAAIAAgDIgCgDIgEgBIgCABg");
	this.shape_18.setTransform(268.7,-515.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("AAGARIgBgBIAAgNIgBgEQAAAAgBgBQAAAAAAAAQgBAAgBAAQAAgBgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAAAABQAAABAAABIAAANIgBABIgDAAIgBgBIAAgfIABgBIADAAIABABIAAAMIACgCIADgBQAEAAACACQADADAAADIAAAOIgBABg");
	this.shape_19.setTransform(266.1,-516.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AAFAQIgCAAQgDAAgBgCQgBgBAAgEIAAgMIAAgBIgCAAIgBAAIAAgDIABAAIACAAIAAgHIAAgBIADAAIAAABIAAAHIAEAAIABAAIAAADIgBAAIgEAAIAAABIAAAMIABACIACABIABAAIABABIAAADg");
	this.shape_20.setTransform(263.9,-516.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AADARIgBAAQgBAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAgBQAAAAAAgBIAAgaIABgBIACAAIAAABIAAAaIABACIABABIABAAIABAAIAAADg");
	this.shape_21.setTransform(261.4,-516.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("AADARIgBAAQgBAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAgBQAAAAAAgBIAAgaIABgBIACAAIAAABIAAAaIABACIABABIABAAIABAAIAAADg");
	this.shape_22.setTransform(260.1,-516.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#333333").s().p("AgEAMIgCgBIgCgCIAAgDQAAgFACgBQADgBADAAIAFAAIAAAAIAAgCIgBgEQAAAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgDAAIgCACIAAAAIgCgCIAAgBIADgCIAEAAQAFAAACACQADABAAAEIAAAPIgBABIgDAAIgBgBIAAgCIgCACIgEABIgDAAgAgDACQAAAAgBABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAABABQAAAAAAABQAAAAAAAAQABABAAAAIADABQAAAAABAAQABAAAAAAQABgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAgDIAAAAIgEAAIgEABg");
	this.shape_23.setTransform(258,-515.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#333333").s().p("AgGARIgBgBIAAgDIABgBIAAAAIADAAIACgDIAAgCIgJgWIABgBIADAAIABABIAFAQIAGgQIABgBIADAAQABABAAAAIgKAYIgBAEIgBACIgCABIgCABg");
	this.shape_24.setTransform(254.3,-515.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#333333").s().p("AgGAMIgBAAIAAgWIABgBIADAAIABABIAAACIACgCIADgBIADAAIACACIAAAAIgCADIgBAAIgBgBIgCAAQgBAAgBAAQAAAAAAAAQAAAAgBABQAAAAAAABIgBAFIAAAMIgBAAg");
	this.shape_25.setTransform(252.3,-515.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#333333").s().p("AgGAMIgBAAIAAgWIABgBIADAAIABABIAAACIACgCIADgBIADAAIACACIAAAAIgCADIgBAAIgBgBIgCAAQgBAAgBAAQAAAAAAAAQAAAAgBABQAAAAAAABIgBAFIAAAMIgBAAg");
	this.shape_26.setTransform(250.2,-515.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#333333").s().p("AgDAMIgEgBIgBgCIgBgDQABgFACgBQACgBAEAAIAFAAIABAAIAAgCIgBgEQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgCAAIgDACIAAAAIgCgCIAAgBIAEgCIADAAQAFAAACACQACABAAAEIAAAPIAAABIgDAAIAAgBIAAgCIgDACIgEABIgCAAgAgDACQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAIADABQAAAAABAAQABAAAAAAQABgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAgBQABAAAAgBIAAgDIgBAAIgFAAIgDABg");
	this.shape_27.setTransform(247.8,-515.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#333333").s().p("AgEALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAIAFABQAAAAABAAQAAAAABABQAAAAABABQAAAAAAAAIAAABIgCACIgBAAIgCgCIgDgBIgCABIgCADIgBADIAAABIAAADIABACQAAAAAAABQAAAAAAABQABAAAAAAQAAAAABABIACABIADgBIACgCIABAAIACACIAAABQAAAAAAAAQgBABAAAAQgBABAAAAQgBAAAAAAIgFABQgCAAgDgBg");
	this.shape_28.setTransform(245.4,-515.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQADACABADIAAADIAAACIAAADIAAADQgBADgDACQgCABgEAAQgCAAgDgBgAgCgHIgCADIgBACIAAACIAAADIABACIACADIACABIAEgBIACgDIAAgCIAAgDIAAgCIAAgCIgCgDIgEgBIgCABg");
	this.shape_29.setTransform(241.7,-515.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#333333").s().p("AAFAQIgCAAQgDAAgBgCQgBgBAAgEIAAgMIAAgBIgCAAIgBAAIAAgDIABAAIACAAIAAgHIAAgBIADAAIAAABIAAAHIAEAAIABAAIAAADIgBAAIgEAAIAAABIAAAMIABACIACABIABAAIABABIAAADg");
	this.shape_30.setTransform(239.7,-516.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#333333").s().p("AgGAMIgBAAIAAgWIABgBIADAAIABABIAAACIACgCIADgBIADAAIACACIAAAAIgCADIgBAAIgBgBIgCAAQgBAAgBAAQAAAAAAAAQAAAAgBABQAAAAAAABIgBAFIAAAMIgBAAg");
	this.shape_31.setTransform(236.8,-515.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQACACABADIABABIAAACIAAACIAAABIAAAAIgOAAIgBAAIAAACIABABIACAEIADABIADgBIADgCIABAAIACACIAAABIgEACIgGABQgCAAgDgBgAgCgHIgCADIgBADIABAAIAKAAIAAAAIAAgDIgCgDIgEgBIgCABg");
	this.shape_32.setTransform(234.4,-515.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#333333").s().p("AAFAQIgCAAQgDAAgBgCQgBgBAAgEIAAgMIAAgBIgCAAIgBAAIAAgDIABAAIACAAIAAgHIAAgBIADAAIAAABIAAAHIAEAAIABAAIAAADIgBAAIgEAAIAAABIAAAMIABACIACABIABAAIABABIAAADg");
	this.shape_33.setTransform(232.3,-516.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#333333").s().p("AAGAMIgBAAIAAgNIgBgFQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAABIAAANIgBAAIgDAAIgBAAIAAgWIABgBIADAAIABABIAAACIACgCIADgBQAEAAACACQADADAAAEIAAAOIgBAAg");
	this.shape_34.setTransform(230.2,-515.8);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQACACABADIABABIAAACIAAACIAAABIAAAAIgOAAIgBAAIAAACIABABIACAEIADABIADgBIADgCIABAAIACACIAAABIgEACIgGABQgCAAgDgBgAgCgHIgCADIgBADIABAAIAKAAIAAAAIAAgDIgCgDIgEgBIgCABg");
	this.shape_35.setTransform(227.6,-515.7);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#333333").s().p("AgEALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAIAFABQAAAAABAAQAAAAABABQAAAAABABQAAAAAAAAIAAABIgCACIgBAAIgCgCIgDgBIgCABIgCADIgBADIAAABIAAADIABACQAAAAAAABQAAAAAAABQABAAAAAAQAAAAABABIACABIADgBIACgCIABAAIACACIAAABQAAAAAAAAQgBABAAAAQgBABAAAAQgBAAAAAAIgFABQgCAAgDgBg");
	this.shape_36.setTransform(225.2,-515.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#333333").s().p("AAFAQIgCAAQgDAAgBgCQgBgBAAgEIAAgMIAAgBIgCAAIgBAAIAAgDIABAAIACAAIAAgHIAAgBIADAAIAAABIAAAHIAEAAIABAAIAAADIgBAAIgEAAIAAABIAAAMIABACIACABIABAAIABABIAAADg");
	this.shape_37.setTransform(222,-516.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#333333").s().p("AAGAMIgBAAIAAgNIgBgFQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAABIAAANIgBAAIgDAAIgBAAIAAgWIABgBIADAAIABABIAAACIACgCIADgBQAEAAACACQADADAAAEIAAAOIgBAAg");
	this.shape_38.setTransform(219.9,-515.8);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQACACABADIABABIAAACIAAACIAAABIAAAAIgOAAIgBAAIAAACIABABIACAEIADABIADgBIADgCIABAAIACACIAAABIgEACIgGABQgCAAgDgBgAgCgHIgCADIgBADIABAAIAKAAIAAAAIAAgDIgCgDIgEgBIgCABg");
	this.shape_39.setTransform(217.3,-515.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#333333").s().p("AANAMIAAAAIAAgNIgBgFQgBAAAAAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAQAAABAAABIAAANIAAAAIgDAAIAAAAIAAgNIgBgFQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAQAAABAAABIAAANIAAAAIgEAAIAAAAIAAgWIAAgBIAEAAIAAABIAAACIADgCIAEgBIAEABIACACIADgCIAFgBQAEAAACACQACADAAAEIAAAOIAAAAg");
	this.shape_40.setTransform(213.9,-515.8);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQACACABADIABABIAAACIAAACIAAABIAAAAIgOAAIgBAAIAAACIABABIACAEIADABIADgBIADgCIABAAIACACIAAABIgEACIgGABQgCAAgDgBgAgCgHIgCADIgBADIABAAIAKAAIAAAAIAAgDIgCgDIgEgBIgCABg");
	this.shape_41.setTransform(210.5,-515.7);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#333333").s().p("AAAAMIgBgBIgIgVIAAgBIADAAIABABIAFAQIAGgQIABgBIADAAIABABIgJAVIAAABg");
	this.shape_42.setTransform(208.1,-515.7);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQADACABADIAAADIAAACIAAADIAAADQgBADgDACQgCABgEAAQgCAAgDgBgAgCgHIgCADIgBACIAAACIAAADIABACIACADIACABIAEgBIACgDIAAgCIAAgDIAAgCIAAgCIgCgDIgEgBIgCABg");
	this.shape_43.setTransform(205.6,-515.7);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#333333").s().p("AgGAMIgBAAIAAgWIABgBIADAAIABABIAAACIACgCIADgBIADAAIACACIAAAAIgCADIgBAAIgBgBIgCAAQgBAAgBAAQAAAAAAAAQAAAAgBABQAAAAAAABIgBAFIAAAMIgBAAg");
	this.shape_44.setTransform(203.6,-515.8);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#333333").s().p("AgJARIAAgBIAAgfIAAAAIAEAAIABAAIAAADIACgDIADgBQADAAACACQACABACADIAAADIAAAEIAAADIAAADIgEAEQgCABgDAAIgDgBIgCgCIAAALIgBABgAgEgIIAAACIAAADIAAADIAAABQABADADAAQAEAAABgDIABgBIAAgDIAAgDIgBgCQgBgEgEAAQgDAAgBAEg");
	this.shape_45.setTransform(201.2,-515.3);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#333333").s().p("AANAMIAAAAIAAgNIgBgFQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAQAAABAAABIAAANIAAAAIgDAAIAAAAIAAgNIgBgFQgBAAAAAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAQAAABAAABIAAANIAAAAIgEAAIAAAAIAAgWIAAgBIAEAAIAAABIAAACIADgCIAEgBIAEABIACACIADgCIAFgBQAEAAACACQACADAAAEIAAAOIAAAAg");
	this.shape_46.setTransform(197.7,-515.8);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#333333").s().p("AgBARIAAgBIAAgVIAAgBIADAAIAAABIAAAVIAAABgAgBgMIAAAAIAAgDIAAgBIADAAIAAABIAAADIAAAAg");
	this.shape_47.setTransform(195,-516.2);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQACACABADIABABIAAACIAAACIAAABIAAAAIgOAAIgBAAIAAACIABABIACAEIADABIADgBIADgCIABAAIACACIAAABIgEACIgGABQgCAAgDgBgAgCgHIgCADIgBADIABAAIAKAAIAAAAIAAgDIgCgDIgEgBIgCABg");
	this.shape_48.setTransform(191.9,-515.7);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#333333").s().p("AANAMIAAAAIAAgNIgBgFQgBAAAAAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAQAAABAAABIAAANIAAAAIgDAAIAAAAIAAgNIgBgFQgBAAAAAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAQAAABAAABIAAANIAAAAIgEAAIAAAAIAAgWIAAgBIAEAAIAAABIAAACIADgCIAEgBIAEABIACACIADgCIAFgBQAEAAACACQACADAAAEIAAAOIAAAAg");
	this.shape_49.setTransform(188.5,-515.8);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQADACABADIAAADIAAACIAAADIAAADQgBADgDACQgCABgEAAQgCAAgDgBgAgCgHIgCADIgBACIAAACIAAADIABACIACADIACABIAEgBIACgDIAAgCIAAgDIAAgCIAAgCIgCgDIgEgBIgCABg");
	this.shape_50.setTransform(185.1,-515.7);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#333333").s().p("AAGARIgBgBIAAgNIgBgEQAAAAgBgBQAAAAAAAAQgBAAgBAAQAAgBgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAAAABQAAABAAABIAAANIgBABIgDAAIgBgBIAAgfIABgBIADAAIABABIAAAMIACgCIADgBQAEAAACACQADADAAADIAAAOIgBABg");
	this.shape_51.setTransform(182.5,-516.2);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#333333").s().p("AADARIgBAAQgBAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAgBQAAAAAAgBIAAgaIAAgBIADAAIAAABIAAAaIABACIABABIABAAIABAAIAAADg");
	this.shape_52.setTransform(179.4,-516.2);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#333333").s().p("AgEAMIgCgBIgCgCIgBgDQAAgFADgBQACgBAEAAIAFAAIAAAAIAAgCIgBgEQAAAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgDAAIgCACIAAAAIgCgCIAAgBIADgCIAEAAQAFAAACACQACABABAEIAAAPIgBABIgDAAIgBgBIAAgCIgCACIgEABIgDAAgAgDACQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAIADABQAAAAABAAQABAAAAAAQABgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAgDIAAAAIgEAAIgEABg");
	this.shape_53.setTransform(177.3,-515.7);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#333333").s().p("AAGAMIgBAAIAAgNIgBgFQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAABIAAANIgBAAIgDAAIgBAAIAAgWIABgBIADAAIABABIAAACIACgCIADgBQAEAAACACQADADAAAEIAAAOIgBAAg");
	this.shape_54.setTransform(174.7,-515.8);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQADACABADIAAADIAAACIAAADIAAADQgBADgDACQgCABgEAAQgCAAgDgBgAgCgHIgCADIgBACIAAACIAAADIABACIACADIACABIAEgBIACgDIAAgCIAAgDIAAgCIAAgCIgCgDIgEgBIgCABg");
	this.shape_55.setTransform(172.1,-515.7);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#333333").s().p("AgBARIAAgBIAAgVIAAgBIADAAIAAABIAAAVIAAABgAgBgMIAAAAIAAgDIAAgBIADAAIAAABIAAADIAAAAg");
	this.shape_56.setTransform(170.2,-516.2);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#333333").s().p("AAFAQIgCAAQgDAAgBgCQgBgBAAgEIAAgMIAAgBIgCAAIgBAAIAAgDIABAAIACAAIAAgHIAAgBIADAAIAAABIAAAHIAEAAIABAAIAAADIgBAAIgEAAIAAABIAAAMIABACIACABIABAAIABABIAAADg");
	this.shape_57.setTransform(168.8,-516.1);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#333333").s().p("AgDAMIgEgBIgBgCIgBgDQABgFACgBQACgBAEAAIAFAAIABAAIAAgCIgBgEQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgCAAIgDACIAAAAIgCgCIAAgBIAEgCIADAAQAFAAACACQACABAAAEIAAAPIAAABIgDAAIAAgBIAAgCIgDACIgEABIgCAAgAgDACQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAIADABQAAAAABAAQABAAAAAAQABgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAgBQABAAAAgBIAAgDIgBAAIgFAAIgDABg");
	this.shape_58.setTransform(166.8,-515.7);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#333333").s().p("AAGAMIgBAAIAAgNIgBgFQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAABIAAANIgBAAIgDAAIgBAAIAAgWIABgBIADAAIABABIAAACIACgCIADgBQAEAAACACQADADAAAEIAAAOIgBAAg");
	this.shape_59.setTransform(164.2,-515.8);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#333333").s().p("AgGARIgBgBIAAgDIABgBIAAAAIADAAIACgDIAAgCIgJgWIABgBIADAAIABABIAFAQIAGgQIABgBIADAAQABABAAAAIgKAYIgBAEIgBACIgCABIgCABg");
	this.shape_60.setTransform(160.4,-515.3);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#333333").s().p("AADARIgBAAQgBAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAgBQAAAAAAgBIAAgaIAAgBIADAAIAAABIAAAaIABACIABABIABAAIABAAIAAADg");
	this.shape_61.setTransform(158.7,-516.2);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#333333").s().p("AAGAMIgBAAIAAgNIgBgFQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAABIAAANIgBAAIgDAAIgBAAIAAgWIABgBIADAAIABABIAAACIACgCIADgBQAEAAACACQADADAAAEIAAAOIgBAAg");
	this.shape_62.setTransform(156.6,-515.8);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQADACABADIAAADIAAACIAAADIAAADQgBADgDACQgCABgEAAQgCAAgDgBgAgCgHIgCADIgBACIAAACIAAADIABACIACADIACABIAEgBIACgDIAAgCIAAgDIAAgCIAAgCIgCgDIgEgBIgCABg");
	this.shape_63.setTransform(153.9,-515.7);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQACACABADIABABIAAACIAAACIAAABIAAAAIgOAAIgBAAIAAACIABABIACAEIADABIADgBIADgCIABAAIACACIAAABIgEACIgGABQgCAAgDgBgAgCgHIgCADIgBADIABAAIAKAAIAAAAIAAgDIgCgDIgEgBIgCABg");
	this.shape_64.setTransform(150.2,-515.7);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#333333").s().p("AAGARIgBgBIAAgNIgBgEQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAAAABQAAABAAABIAAANIgBABIgDAAIgBgBIAAgfIABgBIADAAIABABIAAAMIACgCIADgBQAEAAACACQADADAAADIAAAOIgBABg");
	this.shape_65.setTransform(147.6,-516.2);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#333333").s().p("AAFAQIgCAAQgDAAgBgCQgBgBAAgEIAAgMIAAgBIgCAAIgBAAIAAgDIABAAIACAAIAAgHIAAgBIADAAIAAABIAAAHIAEAAIABAAIAAADIgBAAIgEAAIAAABIAAAMIABACIACABIABAAIABABIAAADg");
	this.shape_66.setTransform(145.4,-516.1);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#333333").s().p("AgCAMIgDgBIgCgBIgCgBIAAgBIACgCIABAAIADACIADABIAEgBQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAIgBgCIgEgBIgCgBQgDAAgCgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgDADgCQACgCADAAIAFAAIAEACIAAABIgCACIgBAAIgDgBIgDgBIgDABIgBACIABADIADABIADAAQADAAACABQAAAAABABQAAABAAAAQABABAAAAQAAABAAAAQAAAEgDACQgCACgFAAIgCAAg");
	this.shape_67.setTransform(142.2,-515.7);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#333333").s().p("AgBARIAAgBIAAgVIAAgBIADAAIAAABIAAAVIAAABgAgBgMIAAAAIAAgDIAAgBIADAAIAAABIAAADIAAAAg");
	this.shape_68.setTransform(140.4,-516.2);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#333333").s().p("AgCAMIgDgBIgCgBIgCgBIAAgBIACgCIABAAIADACIADABIAEgBQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAIgBgCIgEgBIgCgBQgDAAgCgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgDADgCQACgCADAAIAFAAIAEACIAAABIgCACIgBAAIgDgBIgDgBIgDABIgBACIABADIADABIADAAQADAAACABQAAAAABABQAAABAAAAQABABAAAAQAAABAAAAQAAAEgDACQgCACgFAAIgCAAg");
	this.shape_69.setTransform(137.4,-515.7);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#333333").s().p("AgBAEIAAgHIABgBIACAAIAAABIAAADIAAABIAAAAIgCADIAAAAIgBAAg");
	this.shape_70.setTransform(135.7,-517.5);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQACACABADIABABIAAACIAAACIAAABIAAAAIgOAAIgBAAIAAACIABABIACAEIADABIADgBIADgCIABAAIACACIAAABIgEACIgGABQgCAAgDgBgAgCgHIgCADIgBADIABAAIAKAAIAAAAIAAgDIgCgDIgEgBIgCABg");
	this.shape_71.setTransform(133.8,-515.7);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#333333").s().p("AAGAMIgBgBIgFgQIgFAQIAAABIgDAAIgBgBIgHgVIAAgBIAEAAIAAABIAGAQIAFgQIABgBIABAAIABABIAFAQIAGgQIAAgBIAEAAIAAABIgIAVIAAABg");
	this.shape_72.setTransform(130.7,-515.7);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#333333").s().p("AgFALQgCgCgBgDIgBgDIAAgDIAAgCIABgDQABgDACgCQADgBACAAQAEAAACABQADACABADIAAADIAAACIAAADIAAADQgBADgDACQgCABgEAAQgCAAgDgBgAgCgHIgCADIgBACIAAACIAAADIABACIACADIACABIAEgBIACgDIAAgCIAAgDIAAgCIAAgCIgCgDIgEgBIgCABg");
	this.shape_73.setTransform(127.6,-515.7);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#333333").s().p("AgJARIgBgBIAAgfIABgBIADAAIABABIAAAcIAAAAIAPAAIABABIAAACIgBABg");
	this.shape_74.setTransform(125.1,-516.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6,-520.8,320.7,10);


(lib.cabot_gold = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Cabot_LG();
	this.instance.parent = this;
	this.instance.setTransform(0,3,0.342,0.342);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,3,53.4,65.4);


(lib.button_hoover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// SHOP NOW
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAQAnIgQg2IgPA2IgKAAIgVhNIANAAIAOA3IAPg3IAJAAIAQA3IANg3IANAAIgVBNg");
	this.shape.setTransform(75.2,12.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgTAgQgGgGgBgHIgBgTQAAgNABgEQABgIAGgFQAIgJALAAQANAAAHAJQAGAFACAIIAAARIAAATQgCAHgGAGQgHAIgNAAQgLAAgIgIgAgKgXQgEADgBAFIgBAPIABARQABAEAEADQAEAFAGAAQAHAAAEgFQADgDACgEIABgRIgBgPQgCgFgDgDQgEgFgHAAQgGAAgEAFg");
	this.shape_1.setTransform(66.9,12.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AATAnIgjg2IAAA2IgNAAIAAhNIALAAIAkA2IAAg2IAMAAIAABNg");
	this.shape_2.setTransform(59.4,12.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaAnIAAhNIAdAAQAKAAAHAHQAIAGAAALQAAAKgIAGQgHAGgKAAIgSAAIAAAfgAgPgBIARAAQAGAAAEgEQADgDAAgGQAAgGgDgEQgEgDgGAAIgRAAg");
	this.shape_3.setTransform(49.7,12.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgUAgQgFgGgBgHIgBgTQAAgNABgEQABgIAFgFQAJgJALAAQAMAAAJAJQAFAFACAIIAAARIAAATQgCAHgFAGQgJAIgMAAQgLAAgJgIgAgLgXQgDADAAAFIgBAPIABARQAAAEADADQAFAFAGAAQAHAAAFgFQACgDABgEIABgRIgBgPQgBgFgCgDQgFgFgHAAQgGAAgFAFg");
	this.shape_4.setTransform(42.4,12.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAQAnIAAgiIgfAAIAAAiIgMAAIAAhNIAMAAIAAAhIAfAAIAAghIAMAAIAABNg");
	this.shape_5.setTransform(35.1,12.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgbAeIAIgIQAHAHAMAAQAIAAAEgDQAEgDAAgGQAAgFgDgDQgDgCgFgBIgJgCQgJgBgGgEQgFgFAAgKQAAgKAHgGQAHgHALAAQAPAAAJAJIgHAIQgHgGgKAAQgGAAgEADQgEADAAAGQAAAEADADQADADAGABIAIABQAKABAFAEQAGAFAAALQAAALgIAGQgIAGgMAAQgRAAgKgKg");
	this.shape_6.setTransform(27.9,12.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Layer 1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0471AF").s().p("AoRCCIAAkDIQjAAIAAEDg");
	this.shape_7.setTransform(53,13);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#004990").s().p("AoRCCIAAkDIQjAAIAAEDg");
	this.shape_8.setTransform(53,13);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7}]}).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_7}]},1).to({state:[]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.4,0,106.5,26);


(lib.button_cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CC00").s().p("ArECSIAAkjIWIAAIAAEjg");
	this.shape.setTransform(164,25,2.315,1.715);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("rgba(193,220,235,0)").ss(0.1,1,1).p("A4/j5MAx/AAAIAAHzMgx/AAAIAAjR");
	this.shape_1.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Tween5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.button_hoover();
	this.instance.parent = this;
	this.instance.setTransform(-234.3,-83.1,1,1,0,0,0,53,13);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.button_hoover(), 3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(193,220,235,0)").ss(0.1,1,1).p("AIfh/IACAAIAAD/IgCAAAoFCAIgbAAIAAj/IAbAA");
	this.shape.setTransform(-164.5,61.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-287.8,-96.1,178.8,171.4);


(lib.lowes_logo_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol1();
	this.instance.parent = this;
	this.instance.setTransform(41.6,-11.2,0.589,0.587,0,0,0,78.5,19.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.6,-22.7,93,23.5);


// stage content:
(lib.paint_lineup_320x50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		if ( ! this.alreadyExecuted) {
		  this.alreadyExecuted = true;
		  this.loopNumber = 0;
		} else {
		  this.loopNumber++;
		  if (this.loopNumber == 1) {
		    this.stop();
		  }
		}
	}
	this.frame_259 = function() {
		if ( ! this.alreadyExecuted) {
		  this.alreadyExecuted = true;
		  this.loopNumber = 0;
		} else {
		  this.loopNumber++;
		  if (this.loopNumber == 1) {
		    this.stop();
		  }
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(259).call(this.frame_259).wait(1));

	// Clicktag
	this.button_cta = new lib.button_cta();
	this.button_cta.name = "button_cta";
	this.button_cta.parent = this;
	this.button_cta.setTransform(155.1,143.5,0.993,1.119,0,0,0,157.8,131.6);
	new cjs.ButtonHelper(this.button_cta, 0, 1, 2, false, new lib.button_cta(), 3);

	this.timeline.addTween(cjs.Tween.get(this.button_cta).wait(260));

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AY7j0IAAHpMgx1AAAIAAnpg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(260));

	// Text
	this.instance = new lib.FR1copy();
	this.instance.parent = this;
	this.instance.setTransform(272,9.1,1,1,0,0,0,324.6,-75.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(81).to({_off:false},0).wait(1).to({regX:118.2,regY:-59.8,x:65.6,y:24.4,alpha:0.05},0).wait(1).to({alpha:0.1},0).wait(1).to({alpha:0.15},0).wait(1).to({alpha:0.2},0).wait(1).to({alpha:0.25},0).wait(1).to({alpha:0.3},0).wait(1).to({alpha:0.35},0).wait(1).to({alpha:0.4},0).wait(1).to({alpha:0.45},0).wait(1).to({alpha:0.5},0).wait(1).to({alpha:0.55},0).wait(1).to({alpha:0.6},0).wait(1).to({alpha:0.65},0).wait(1).to({alpha:0.7},0).wait(1).to({alpha:0.75},0).wait(1).to({alpha:0.8},0).wait(1).to({alpha:0.85},0).wait(1).to({alpha:0.9},0).wait(1).to({alpha:0.95},0).wait(1).to({alpha:1},0).wait(69).to({alpha:0.909},0).wait(1).to({alpha:0.818},0).wait(1).to({alpha:0.727},0).wait(1).to({alpha:0.637},0).wait(1).to({alpha:0.546},0).wait(1).to({alpha:0.455},0).wait(1).to({alpha:0.364},0).wait(1).to({alpha:0.273},0).wait(1).to({alpha:0.182},0).wait(1).to({alpha:0.091},0).wait(1).to({alpha:0.001},0).to({_off:true},1).wait(79));

	// Logo
	this.instance_1 = new lib.Tween1("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(677.9,27.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({regX:-401,regY:-4.3,x:276.9,y:22.9},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({alpha:0.75},0).wait(1).to({alpha:0.5},0).wait(1).to({alpha:0.25},0).wait(1).to({alpha:0},0).to({_off:true},1).wait(164));

	// Purdy  copy
	this.instance_2 = new lib.purdy_brush("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(13.7,61.8,0.421,0.421,0,0,0,8.8,50.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({regX:6.8,regY:71.2,x:12.8,y:66},0).wait(1).to({y:61.5},0).wait(1).to({y:57},0).wait(1).to({y:52.5},0).wait(1).to({y:48},0).wait(1).to({y:43.5},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:47.1},0).wait(1).to({y:50.7},0).wait(1).to({y:54.2},0).wait(1).to({y:57.8},0).wait(1).to({y:61.3},0).wait(1).to({y:64.9},0).wait(1).to({y:68.4},0).wait(1).to({y:72},0).wait(1).to({y:75.5},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:67.2},0).wait(1).to({y:58.9},0).wait(1).to({y:50.5},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:53.1},0).wait(1).to({y:55.6},0).wait(1).to({y:58.1},0).wait(1).to({y:60.7},0).wait(1).to({y:63.2},0).wait(1).to({y:65.7},0).wait(1).to({y:68.3},0).wait(1).to({y:70.8},0).wait(1).to({y:73.3},0).wait(1).to({y:75.9},0).wait(1).to({y:78.4},0).wait(1).to({y:80.9},0).wait(1).to({y:83.5},0).wait(1).to({y:86},0).wait(1).to({y:88.5},0).to({_off:true},1).wait(167));

	// Minwax  copy
	this.instance_3 = new lib.minwax_wood("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(44.5,70.8,0.559,0.559,0,0,0,31.6,38.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1).to({regX:26.3,regY:41.3,x:41.5,y:67.7},0).wait(1).to({y:63.2},0).wait(1).to({y:58.7},0).wait(1).to({y:54.2},0).wait(1).to({y:49.7},0).wait(1).to({y:45.2},0).wait(1).to({y:43.2},0).wait(1).to({y:41.2},0).wait(1).to({y:39.2},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:42.8},0).wait(1).to({y:46.4},0).wait(1).to({y:49.9},0).wait(1).to({y:53.5},0).wait(1).to({y:57},0).wait(1).to({y:60.6},0).wait(1).to({y:64.1},0).wait(1).to({y:67.7},0).wait(1).to({y:71.2},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:62.9},0).wait(1).to({y:54.6},0).wait(1).to({y:46.2},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:47.9},0).wait(1).to({y:49.6},0).wait(1).to({y:51.2},0).wait(1).to({y:52.9},0).wait(1).to({y:54.6},0).wait(1).to({y:56.2},0).wait(1).to({y:57.9},0).wait(1).to({y:59.6},0).wait(1).to({y:61.2},0).wait(1).to({y:62.9},0).wait(1).to({y:64.6},0).wait(1).to({y:66.2},0).wait(1).to({y:67.9},0).wait(1).to({y:69.6},0).wait(1).to({y:71.2},0).to({_off:true},1).wait(167));

	// Sherwin  copy
	this.instance_4 = new lib.sherwin_infinity("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(83.9,69.9,0.58,0.58,0,0,0,35.5,42.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1).to({regX:30,regY:50.1,x:80.6},0).wait(1).to({y:65.4},0).wait(1).to({y:60.9},0).wait(1).to({y:56.4},0).wait(1).to({y:51.9},0).wait(1).to({y:47.4},0).wait(1).to({y:43.4},0).wait(1).to({y:39.4},0).wait(1).to({y:31.4},0).wait(1).to({y:30.7},0).wait(1).to({y:30.1},0).wait(1).to({y:29.4},0).wait(1).to({y:28.8},0).wait(1).to({y:28.1},0).wait(1).to({y:27.4},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:32.2},0).wait(1).to({y:37},0).wait(1).to({y:41.8},0).wait(1).to({y:46.6},0).wait(1).to({y:51.4},0).wait(1).to({y:56.2},0).wait(1).to({y:61},0).wait(1).to({y:65.8},0).wait(1).to({y:70.6},0).wait(1).to({y:75.4},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:67.1},0).wait(1).to({y:58.7},0).wait(1).to({y:50.4},0).wait(1).to({y:47.1},0).wait(1).to({y:43.7},0).wait(1).to({y:40.4},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:42.9},0).wait(1).to({y:45.3},0).wait(1).to({y:47.8},0).wait(1).to({y:50.3},0).wait(1).to({y:52.7},0).wait(1).to({y:55.2},0).wait(1).to({y:57.7},0).wait(1).to({y:60.1},0).wait(1).to({y:62.6},0).wait(1).to({y:65.1},0).wait(1).to({y:67.5},0).wait(1).to({y:70},0).wait(1).to({y:72.5},0).wait(1).to({y:74.9},0).wait(1).to({y:77.4},0).to({_off:true},1).wait(167));

	// Cabot  copy
	this.instance_5 = new lib.cabot_gold("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(124.1,70.6,0.552,0.552,0,0,0,30.1,33);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({regX:26.7,regY:35.7,x:122.2,y:67.5},0).wait(1).to({y:63},0).wait(1).to({y:58.5},0).wait(1).to({y:54},0).wait(1).to({y:49.5},0).wait(1).to({y:45},0).wait(1).to({y:43},0).wait(1).to({y:41},0).wait(1).to({y:39},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:42.6},0).wait(1).to({y:46.2},0).wait(1).to({y:49.7},0).wait(1).to({y:53.3},0).wait(1).to({y:56.8},0).wait(1).to({y:60.4},0).wait(1).to({y:63.9},0).wait(1).to({y:67.5},0).wait(1).to({y:71},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:62.7},0).wait(1).to({y:54.4},0).wait(1).to({y:46},0).wait(1).to({y:39},0).wait(1).to({y:32},0).wait(1).to({y:28},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:31},0).wait(1).to({y:33.9},0).wait(1).to({y:36.8},0).wait(1).to({y:39.8},0).wait(1).to({y:42.7},0).wait(1).to({y:45.6},0).wait(1).to({y:48.6},0).wait(1).to({y:51.5},0).wait(1).to({y:54.4},0).wait(1).to({y:57.4},0).wait(1).to({y:60.3},0).wait(1).to({y:63.2},0).wait(1).to({y:66.2},0).wait(1).to({y:69.1},0).wait(1).to({y:72},0).to({_off:true},1).wait(167));

	// Kyrlon copy
	this.instance_6 = new lib.krylon_fusion("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(155.5,66.2,0.572,0.573,0,0,0,17.4,43.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({regX:19.3,regY:51.9,x:156.5,y:66.6},0).wait(1).to({y:62.1},0).wait(1).to({y:57.6},0).wait(1).to({y:53.1},0).wait(1).to({y:48.6},0).wait(1).to({y:44.1},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:47.7},0).wait(1).to({y:51.2},0).wait(1).to({y:54.8},0).wait(1).to({y:58.3},0).wait(1).to({y:61.9},0).wait(1).to({y:65.4},0).wait(1).to({y:69},0).wait(1).to({y:72.5},0).wait(1).to({y:76.1},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:67.8},0).wait(1).to({y:59.4},0).wait(1).to({y:51.1},0).wait(1).to({y:48.1},0).wait(1).to({y:45.1},0).wait(1).to({y:42.1},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:44.4},0).wait(1).to({y:46.6},0).wait(1).to({y:48.9},0).wait(1).to({y:51.2},0).wait(1).to({y:53.4},0).wait(1).to({y:55.7},0).wait(1).to({y:58},0).wait(1).to({y:60.2},0).wait(1).to({y:62.5},0).wait(1).to({y:64.8},0).wait(1).to({y:67},0).wait(1).to({y:69.3},0).wait(1).to({y:71.6},0).wait(1).to({y:73.8},0).wait(1).to({y:76.1},0).to({_off:true},1).wait(167));

	// Valspar  copy
	this.instance_7 = new lib.valspar_dura("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(187.2,70.1,0.453,0.453,0,0,0,34.8,43.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1).to({regX:33.3,regY:44.9,x:186.4,y:66},0).wait(1).to({y:61.5},0).wait(1).to({y:57},0).wait(1).to({y:52.5},0).wait(1).to({y:48},0).wait(1).to({y:43.5},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:47.1},0).wait(1).to({y:50.7},0).wait(1).to({y:54.2},0).wait(1).to({y:57.8},0).wait(1).to({y:61.3},0).wait(1).to({y:64.9},0).wait(1).to({y:68.4},0).wait(1).to({y:72},0).wait(1).to({y:75.5},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:67.2},0).wait(1).to({y:58.9},0).wait(1).to({y:50.5},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:51.9},0).wait(1).to({y:53.2},0).wait(1).to({y:54.5},0).wait(1).to({y:55.9},0).wait(1).to({y:57.2},0).wait(1).to({y:58.5},0).wait(1).to({y:59.9},0).wait(1).to({y:61.2},0).wait(1).to({y:62.5},0).wait(1).to({y:63.9},0).wait(1).to({y:65.2},0).wait(1).to({y:66.5},0).wait(1).to({y:67.9},0).wait(1).to({y:69.2},0).wait(1).to({y:70.5},0).to({_off:true},1).wait(167));

	// Thompson copy
	this.instance_8 = new lib.thopson_waterseal("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(225.4,73.7,0.498,0.498,0,0,0,34.6,46.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(1).to({regX:28.7,regY:39.5,x:222.4,y:65.6},0).wait(1).to({y:61.1},0).wait(1).to({y:56.6},0).wait(1).to({y:52.1},0).wait(1).to({y:47.6},0).wait(1).to({y:43.1},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:46.7},0).wait(1).to({y:50.2},0).wait(1).to({y:53.8},0).wait(1).to({y:57.3},0).wait(1).to({y:60.9},0).wait(1).to({y:64.4},0).wait(1).to({y:68},0).wait(1).to({y:71.5},0).wait(1).to({y:75.1},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:66.8},0).wait(1).to({y:58.4},0).wait(1).to({y:50.1},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({y:51.7},0).wait(1).to({y:53.3},0).wait(1).to({y:54.9},0).wait(1).to({y:56.5},0).wait(1).to({y:58.1},0).wait(1).to({y:59.7},0).wait(1).to({y:61.3},0).wait(1).to({y:62.9},0).wait(1).to({y:64.5},0).wait(1).to({y:66.1},0).wait(1).to({y:67.7},0).wait(1).to({y:69.3},0).wait(1).to({y:70.9},0).wait(1).to({y:72.5},0).wait(1).to({y:74.1},0).to({_off:true},1).wait(167));

	// line-up
	this.instance_9 = new lib.paint_lineup("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(-605.5,390.1,2.745,2.745,0,0,0,112.3,69.7);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(97).to({_off:false},0).wait(1).to({regX:412,regY:-93.7,x:216.9,y:-53.7},0).wait(1).to({x:216.7,y:-48.9},0).wait(1).to({x:216.4,y:-44.1},0).wait(1).to({x:216.2,y:-39.4},0).wait(1).to({x:215.9,y:-34.6},0).wait(1).to({x:215.6,y:-29.8},0).wait(1).to({x:215.4,y:-25.1},0).wait(1).to({x:215.1,y:-20.3},0).wait(1).to({x:214.9,y:-15.5},0).wait(1).to({x:214.6,y:-10.8},0).wait(1).to({x:214.3,y:-6},0).wait(1).to({x:214.1,y:-1.2},0).wait(1).to({x:213.8,y:3.5},0).wait(1).to({x:213.6,y:8.3},0).wait(1).to({x:213.3,y:13.1},0).wait(1).to({x:213.1,y:17.8},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

	// Disclaimer
	this.instance_10 = new lib.Disclaimer("synched",0);
	this.instance_10.parent = this;
	this.instance_10.setTransform(79.7,577.2,1,1,0,0,0,76,16.2);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(105).to({_off:false},0).wait(1).to({regX:218.2,regY:-515.8,x:221.9,y:45.2,alpha:0.125},0).wait(1).to({alpha:0.25},0).wait(1).to({alpha:0.375},0).wait(1).to({alpha:0.5},0).wait(1).to({alpha:0.625},0).wait(1).to({alpha:0.75},0).wait(1).to({alpha:0.875},0).wait(1).to({alpha:1},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

	// button
	this.instance_11 = new lib.Tween5("synched",0);
	this.instance_11.parent = this;
	this.instance_11.setTransform(203.4,89.8,0.608,0.608);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(214).to({_off:false},0).wait(1).to({regX:-198.5,regY:-10.7,x:82.7,y:83.3,alpha:0.071},0).wait(1).to({alpha:0.143},0).wait(1).to({alpha:0.214},0).wait(1).to({alpha:0.286},0).wait(1).to({alpha:0.357},0).wait(1).to({alpha:0.429},0).wait(1).to({alpha:0.5},0).wait(1).to({alpha:0.571},0).wait(1).to({alpha:0.643},0).wait(1).to({alpha:0.714},0).wait(1).to({alpha:0.786},0).wait(1).to({alpha:0.857},0).wait(1).to({alpha:0.929},0).wait(1).to({alpha:1},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

	// Logo
	this.instance_12 = new lib.lowes_logo_2("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(98,47,1,1,0,0,0,79,20);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(174).to({_off:false},0).wait(1).to({regX:41.8,regY:-11,x:60.8,y:16,alpha:0.111},0).wait(1).to({alpha:0.222},0).wait(1).to({alpha:0.333},0).wait(1).to({alpha:0.444},0).wait(1).to({alpha:0.556},0).wait(1).to({alpha:0.667},0).wait(1).to({alpha:0.778},0).wait(1).to({alpha:0.889},0).wait(1).to({alpha:1},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

	// Background
	this.instance_13 = new lib._05_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(-1,-1);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(260));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(157.3,20.3,326.8,101.9);
// library properties:
lib.properties = {
	id: '9A27E2F3A84F463E9869F4B5E2AF43DD',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/_05_1.jpg", id:"_05_1"},
		{src:"images/_300x250_paint_group_lineup.png", id:"_300x250_paint_group_lineup"},
		{src:"images/Cabot_LG.png", id:"Cabot_LG"},
		{src:"images/Krylon_LG.png", id:"Krylon_LG"},
		{src:"images/lowes_blue_solid.png", id:"lowes_blue_solid"},
		{src:"images/lowes_blue_solidpngcopy.png", id:"lowes_blue_solidpngcopy"},
		{src:"images/Minwax_LG.png", id:"Minwax_LG"},
		{src:"images/Purdy_LG.png", id:"Purdy_LG"},
		{src:"images/Sherwin_LG.png", id:"Sherwin_LG"},
		{src:"images/Thompsons_LG.png", id:"Thompsons_LG"},
		{src:"images/Valspar_LG.png", id:"Valspar_LG"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['9A27E2F3A84F463E9869F4B5E2AF43DD'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;