(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bob = function() {
	this.initialize(img.bob);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1786,1191);


(lib.L880302pPreview = function() {
	this.initialize(img.L880302pPreview);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,600);


(lib.logo_lowes_blue2_68x148 = function() {
	this.initialize(img.logo_lowes_blue2_68x148);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,148,68);


(lib.mtape = function() {
	this.initialize(img.mtape);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1902,1296);


(lib.white_gradient = function() {
	this.initialize(img.white_gradient);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,298,210);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.white_gradient_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.white_gradient();
	this.instance.parent = this;
	this.instance.setTransform(-3,212.3,0.853,1.444,-90);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3,-42,303.2,254.3);


(lib.Tween6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.L880302pPreview();
	this.instance.parent = this;
	this.instance.setTransform(-211.5,-211.5,0.705,0.705);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-211.5,-211.5,423,423);


(lib.Tween5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Tween4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.logo_lowes_blue2_68x148();
	this.instance.parent = this;
	this.instance.setTransform(-28.3,-13,0.383,0.382);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28.3,-13,56.6,26);


(lib.Tween3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#004990").ss(1,1,1).p("A4f0QMAw/AAAQAAACACAAMAAAAodQgCAAAAACMgw/AAAQAAgCgCAAMAAAgodQACAAAAgCg");
	this.shape.setTransform(0.6,0.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#004792").s().p("A4fURQAAAAAAgBQAAAAAAAAQgBgBAAAAQgBAAAAAAMAAAgodQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBAAAAMAw/AAAQAAAAAAABQAAAAAAAAQABAAAAABQABAAAAAAMAAAAodQAAAAgBAAQAAAAgBABQAAAAAAAAQAAABAAAAg");
	this.shape_1.setTransform(0.6,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-157.4,-130.2,316.1,261.5);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.logo_lowes_blue2_68x148();
	this.instance.parent = this;
	this.instance.setTransform(-28.3,-13,0.383,0.382);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28.3,-13,56.6,26);


(lib.start_w_lowes_stack = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgZA8IgPgEIAAAAIAAgcIAAAAIAOAFQAQAFAHABIADAAQAKAAABgHQADgHgJgFIgNgHQgXgKgIgMQgEgJABgKQAAgKAFgHQAMgSAYAAIAFABQASACARALIABAAIAAAaIgBAAIgRgHQgLgFgKAAQgGAAgDADQgEAEABADQACAHANAGIABAAQAbALAHAOIAAAAIABABIAAAAQADAHAAAIQAAASgNAKQgIAHgSAAQgMAAgRgEg");
	this.shape.setTransform(261.1,33.7,1.522,1.546);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAMA7QgFAAgDgDQgEgDAAgEQAAAEgCADQgFADgEAAIgmAAQgGAAgFgEQgEgFAAgGIAAhmIAgAAIAABZIATAAIAAhZIAbAAIAABZIAUAAIAAhZIAfAAIAABmQAAAGgEAFQgFAEgGAAg");
	this.shape_1.setTransform(226,33.7,1.522,1.546);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeA7QgGAAgEgEQgFgFAAgGIAAhXQAAgHAFgEQAEgEAGAAIA9AAQAGAAAEAEQAFAEAAAHIAABXQAAAGgFAFQgEAEgGAAgAgNAfIAbAAIAAg+IgbAAg");
	this.shape_2.setTransform(206.4,33.7,1.522,1.546);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AglA7IAAh1IBLAAIAAAbIgrAAIAAATIArAAIAAAZIgrAAIAAASIArAAIAAAcg");
	this.shape_3.setTransform(244.5,33.7,1.522,1.546);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgoBIIAAiPIAgAAIAABzIAwAAIAAAcg");
	this.shape_4.setTransform(191.3,31.7,1.522,1.546);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgGAHQgDgDAAgEQAAgJAJAAQAEAAADADQADADAAADQAAAEgDADQgDADgEAAQgDAAgDgDgAgHAAQAAAIAHAAQAIAAAAgIQAAgHgIAAQgHAAAAAHgAADAGIgDgFIgBAAIAAAFIgCAAIAAgLIAEAAQAEAAAAAEQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBABIADAFgAgBAAIABAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAAAgBAAIgBAAg");
	this.shape_5.setTransform(269.5,25.9,1.522,1.546);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMARIAAghIAZAAIgEAhg");
	this.shape_6.setTransform(253.3,23.2,1.522,1.546);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AlbCgIAAjTIA5AAIAAgfIBwAAICyhNIC0BNIBwAAIAAAfIA4AAIAADTgAlMCRIKZAAIAAi1Ig4AAIAAgfIhkAAIiwhMIiwBMIhlAAIAAAfIg4AAg");
	this.shape_7.setTransform(226,24.7,1.522,1.546);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAZBEQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAg1QAAAAAAAAQAAAAAAAAQgBAAAAAAQAAgBgBAAIgqAAIgBABIAAA1QAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgZAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAiDQAAgBAAAAQAAAAAAAAQABgBAAAAQABAAAAAAIAZAAQAAAAABAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAzIABABIAqAAQABAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAIAAgzQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAZAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAACDQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_8.setTransform(153.2,35.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgMBEQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhqQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAgBAAIgiAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAgWQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAAAIBiAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAWQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIghAAQgBAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIAABqQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_9.setTransform(135.8,35.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgLBEQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAiDQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAYAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAACDQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_10.setTransform(122.1,35.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAaBEQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgYhTIAAAAIgXBTQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgUAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgjiDQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAZAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIATBUIAAAAIAXhUQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIAYBUIAAAAIAThUQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAZAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIgjCDQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAg");
	this.shape_11.setTransform(105.4,35.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgLBEQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhqQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAgBAAIgiAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAgWQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAAAIBiAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAWQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIghAAQgBAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAABqQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_12.setTransform(76.5,35.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAWBEQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBIgWgyIgSAAQAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAABIAAAwQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgZAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAiDQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIA0AAQAVAAANAMQAMALAAATQAAANgGAKQgHAJgLAFIAbA1QAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAgAgWgpIAAAgIABABIAXAAQAIAAAFgFQAFgEAAgIQAAgHgFgFQgFgFgIAAIgXAAQAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAAAg");
	this.shape_13.setTransform(59.8,35.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAhBEQAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIgIgYIguAAIgHAYQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAIgbAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAABgBIAtiDQABgBAAAAQAAAAAAAAQABgBAAAAQABAAAAAAIAYAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIAtCDQABABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAgAAPARIgOguIgBAAIgOAuIAdAAg");
	this.shape_14.setTransform(41.5,35.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgMBEQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhqQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAgBAAIgiAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAgWQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAAAIBiAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAWQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIghAAQgBAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIAABqQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_15.setTransform(25.5,35.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgdBBQgNgFgIgIQgBgBAAAAQAAAAgBgBQAAAAABgBQAAAAAAgBIAPgRQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAABQASAOAQAAQALAAAGgFQAFgEAAgHQAAgNgUgDIgHgBQgqgGAAghQAAgTANgMQANgLAVAAQAbAAASAOQAAAAABABQAAAAAAAAQAAABAAAAQgBABAAAAIgMASQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQgQgKgPAAQgIAAgFAEQgEAEAAAGQAAAMAUADIAHABQAqAGAAAjQAAATgNALQgPAMgZAAQgOAAgPgFg");
	this.shape_16.setTransform(8.8,35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,279,50);


(lib.FR3copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#004792").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape.setTransform(-41.4,107.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#004792").s().p("AgLA9IAAhjIgfAAIAAgVIBVAAIAAAVIgfAAIAABjg");
	this.shape_1.setTransform(-48.7,102.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#004792").s().p("AgfAxQgJgJgCgNQgCgHAAgUQAAgTACgIQACgMAJgIQAMgOATAAQARAAANAKQAMAKACATIgXAAQgFgSgQABQgIAAgGAGQgEAEgBAGQgBAHAAAQQAAARABAHQABAGAEAEQAGAGAIABQAQAAAFgSIAXAAQgDATgMAKQgMAJgRAAQgTABgMgNg");
	this.shape_2.setTransform(-58.6,102.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#004792").s().p("AgnA9IAAh4IBPAAIAAAVIg3AAIAAAcIAuAAIAAAUIguAAIAAAeIA3AAIAAAVg");
	this.shape_3.setTransform(-68.9,102.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#004792").s().p("AgkAwIAPgPQAIAHAIAAQASAAAAgVIAAhPIAYAAIAABQQAAAUgNAKQgMALgRAAQgSAAgNgNg");
	this.shape_4.setTransform(-79.2,102.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#004792").s().p("AggAxQgIgJgCgNQgCgHAAgUQAAgTACgIQACgMAIgIQANgOATAAQATAAAOAOQAIAIACAMQACAIAAATQAAAUgCAHQgCANgIAJQgOANgTgBQgTABgNgNgAgOghQgEAEgBAGQgBAHAAAQQAAARABAHQABAGAEAEQAFAGAJABQAJgBAGgGQAEgEABgGQABgHAAgRQAAgQgBgHQgBgGgEgEQgGgGgJAAQgJAAgFAGg");
	this.shape_5.setTransform(-88.4,102.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#004792").s().p("AASA9IgXgxIgQAAIAAAxIgYAAIAAh4IAuAAQATAAAKALQALAKAAAQQAAAMgHAIQgFAHgLADIAcA1gAgVgHIAVAAQAHABAFgFQAFgFAAgGQAAgIgFgEQgFgEgHAAIgVAAg");
	this.shape_6.setTransform(-98.9,102.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#004792").s().p("AgrA9IAAh4IAuAAQATAAALALQALAKAAAQQAAAQgLAKQgLALgTAAIgVAAIAAAugAgSgFIAUAAQAJAAAEgFQAFgFAAgHQAAgHgFgFQgEgEgJAAIgUAAg");
	this.shape_7.setTransform(-109.8,102.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#004792").s().p("AgLA9IAAhjIgfAAIAAgWIBVAAIAAAWIgfAAIAABjg");
	this.shape_8.setTransform(-3,82.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#004792").s().p("AAZA9IguhKIAABKIgYAAIAAh5IAVAAIAvBKIAAhKIAXAAIAAB5g");
	this.shape_9.setTransform(-13.9,82.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#004792").s().p("AgnA9IAAh5IBPAAIAAAWIg3AAIAAAcIAuAAIAAAUIguAAIAAAdIA3AAIAAAWg");
	this.shape_10.setTransform(-24.8,82.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#004792").s().p("AAfA9IAAhGIgXAtIgPAAIgXgtIAABGIgYAAIAAh5IAXAAIAfBBIAfhBIAYAAIAAB5g");
	this.shape_11.setTransform(-37,82.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#004792").s().p("AgnA9IAAh5IBPAAIAAAWIg3AAIAAAcIAvAAIAAAUIgvAAIAAAdIA3AAIAAAWg");
	this.shape_12.setTransform(-48.8,82.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#004792").s().p("AgIA9Igoh5IAYAAIAYBOIAYhOIAZAAIgoB5g");
	this.shape_13.setTransform(-59.1,82.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#004792").s().p("AggAwQgIgIgCgNQgCgHAAgUQAAgTACgIQACgMAIgIQANgNATgBQATABAOANQAIAIACAMQACAJAAASQAAAUgCAHQgCANgIAIQgOANgTABQgTgBgNgNgAgOghQgEAEgBAGQgBAHAAAQQAAARABAHQABAGAEAEQAFAHAJAAQAJAAAGgHQAEgEABgGQABgHAAgRQAAgQgBgHQgBgGgEgEQgGgHgJABQgJgBgFAHg");
	this.shape_14.setTransform(-69.5,82.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#004792").s().p("AASA9IgXgxIgQAAIAAAxIgYAAIAAh5IAuAAQATAAAKAMQALAKAAAPQAAANgHAIQgFAHgLADIAcA1gAgVgHIAVAAQAHABAFgFQAFgEAAgIQAAgGgFgFQgFgFgHABIgVAAg");
	this.shape_15.setTransform(-80,82.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#004792").s().p("AgrA9IAAh5IAuAAQATAAALAMQALAKAAAQQAAAQgLAKQgLALgTAAIgVAAIAAAugAgSgGIAUAAQAJABAEgFQAFgEAAgIQAAgHgFgFQgEgFgJABIgUAAg");
	this.shape_16.setTransform(-90.9,82.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#004792").s().p("AAfA9IAAhGIgXAtIgPAAIgXgtIAABGIgYAAIAAh5IAXAAIAfBBIAfhBIAYAAIAAB5g");
	this.shape_17.setTransform(-103.5,82.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#004792").s().p("AgLA9IAAh5IAXAAIAAB5g");
	this.shape_18.setTransform(-113,82.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#004792").s().p("AgnA9IAAh5IBPAAIAAAVIg3AAIAAAdIAuAAIAAAUIguAAIAAAdIA3AAIAAAWg");
	this.shape_19.setTransform(-27.8,62.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#004792").s().p("AAfA9IAAhGIgXAtIgPAAIgXgtIAABGIgYAAIAAh5IAXAAIAfBBIAfhBIAYAAIAAB5g");
	this.shape_20.setTransform(-40,62.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#004792").s().p("AggAwQgIgIgCgMQgCgIAAgUQAAgTACgHQACgNAIgJQANgNATABQATgBAOANQAIAJACANQACAHAAATQAAATgCAJQgCAMgIAIQgOAOgTAAQgTAAgNgOgAgOghQgEAEgBAGQgBAHAAAQQAAARABAHQABAGAEAEQAFAHAJgBQAJABAGgHQAEgEABgGQABgHAAgRQAAgQgBgHQgBgGgEgEQgGgHgJAAQgJAAgFAHg");
	this.shape_21.setTransform(-52.4,62.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#004792").s().p("AAUA9IAAgzIgnAAIAAAzIgYAAIAAh5IAYAAIAAAyIAnAAIAAgyIAYAAIAAB5g");
	this.shape_22.setTransform(-63.6,62.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#004792").s().p("AgLA9IAAhkIgfAAIAAgVIBVAAIAAAVIgfAAIAABkg");
	this.shape_23.setTransform(-78.2,62.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#004792").s().p("AAXA9IgXgqIgWAqIgbAAIAlg9Igjg8IAbAAIAUAnIAVgnIAbAAIgjA8IAlA9g");
	this.shape_24.setTransform(-88.2,62.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#004792").s().p("AgnA9IAAh5IBPAAIAAAVIg3AAIAAAdIAuAAIAAAUIguAAIAAAdIA3AAIAAAWg");
	this.shape_25.setTransform(-98.1,62.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#004792").s().p("AAZA9IguhKIAABKIgYAAIAAh5IAVAAIAvBJIAAhJIAXAAIAAB5g");
	this.shape_26.setTransform(-109.6,62.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#004792").s().p("AATA8IgYgwIgQAAIAAAwIgYAAIAAh3IAuAAQASgBALALQALALAAAQQAAALgHAJQgFAHgKAEIAbAzgAgVgGIAVAAQAIgBAEgEQAFgFAAgGQAAgHgFgFQgEgEgIgBIgVAAg");
	this.shape_27.setTransform(-5.1,42.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#004792").s().p("AgfAyQgNgMAAgUIAAhOIAYAAIAABNQAAALAGAGQAFAGAJAAQAKAAAFgGQAGgGAAgLIAAhNIAYAAIAABOQAAAUgNAMQgNALgTAAQgSAAgNgLg");
	this.shape_28.setTransform(-16.8,42.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#004792").s().p("AggAxQgIgJgCgMQgCgIAAgUQAAgTACgHQACgNAIgJQANgNATABQATgBAOANQAIAJACANQACAIAAASQAAAUgCAIQgCAMgIAJQgOAMgTAAQgTAAgNgMgAgOghQgEAEgBAGQgBAHAAAQQAAARABAHQABAGAEAEQAFAGAJAAQAJAAAGgGQAEgEABgGQABgHAAgRQAAgQgBgHQgBgGgEgEQgGgGgJgBQgJABgFAGg");
	this.shape_29.setTransform(-27.9,42.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#004792").s().p("AgKA8IAAgxIglhGIAaAAIAVAwIAXgwIAZAAIgkBGIAAAxg");
	this.shape_30.setTransform(-38.2,42.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#004792").s().p("AgnA8IAAh3IBPAAIAAAUIg3AAIAAAdIAuAAIAAAUIguAAIAAAdIA3AAIAAAVg");
	this.shape_31.setTransform(-51.8,42.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#004792").s().p("AggAxQgJgJgCgMQgBgIAAgUQAAgTABgHQACgNAJgJQANgNATABQATAAAMALQALAKADARIgYAAQgEgSgRAAQgJABgGAGQgDAEgBAGQgCAHAAAQQAAARACAHQABAGADAEQAGAGAJAAQAKABAGgIQAGgGAAgJIAAgFIgWAAIAAgTIAtAAIAAARQAAAZgMAMQgNANgUAAQgTAAgNgMg");
	this.shape_32.setTransform(-62.7,42.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#004792").s().p("AAdA8IgHgVIgqAAIgIAVIgYAAIAsh3IARAAIAsB3gAAPATIgPgrIgOArIAdAAg");
	this.shape_33.setTransform(-73.6,42.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#004792").s().p("AAZA8IguhJIAABJIgYAAIAAh3IAVAAIAvBIIAAhIIAXAAIAAB3g");
	this.shape_34.setTransform(-85,42.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#004792").s().p("AAdA8IgHgVIgqAAIgIAVIgYAAIAsh3IARAAIAsB3gAAPATIgPgrIgOArIAdAAg");
	this.shape_35.setTransform(-96.4,42.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#004792").s().p("AAfA8IAAhFIgXAtIgPAAIgXgtIAABFIgYAAIAAh3IAXAAIAfBAIAfhAIAYAAIAAB3g");
	this.shape_36.setTransform(-108.7,42.9);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#004792").s().p("AggAxQgIgJgCgNQgCgHAAgUQAAgTACgIQACgMAIgJQANgMATAAQATAAAOAMQAIAJACAMQACAIAAATQAAATgCAIQgCANgIAJQgOANgTgBQgTABgNgNgAgOghQgEAEgBAGQgBAHAAAQQAAARABAHQABAGAEAEQAFAGAJABQAJgBAGgGQAEgEABgGQABgHAAgRQAAgQgBgHQgBgGgEgEQgGgGgJAAQgJAAgFAGg");
	this.shape_37.setTransform(-19.4,22.9);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#004792").s().p("AgLA8IAAhjIggAAIAAgUIBXAAIAAAUIggAAIAABjg");
	this.shape_38.setTransform(-29.7,22.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#004792").s().p("AgsAtIAQgPQAKALASAAQAVgBAAgPQAAgGgDgEQgEgDgHgBIgOgCQgPgDgIgGQgJgJAAgPQAAgRAMgJQALgKASAAQAZAAAOANIgOAQQgJgJgQAAQgIAAgFAEQgFAFAAAHQAAAFAEADQAEAEAHABIANACQAPACAIAHQAKAIAAARQAAARgNAKQgNAJgTAAQgcABgQgRg");
	this.shape_39.setTransform(-43.7,22.9);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#004792").s().p("AgfAxQgNgLAAgTIAAhPIAYAAIAABOQAAAKAGAGQAFAGAJAAQAKAAAFgGQAGgGAAgKIAAhOIAYAAIAABPQAAATgNALQgNAMgTAAQgSAAgNgMg");
	this.shape_40.setTransform(-54.2,22.9);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#004792").s().p("AgLA8IAAhjIggAAIAAgUIBWAAIAAAUIgfAAIAABjg");
	this.shape_41.setTransform(-68.6,22.9);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#004792").s().p("AgsAtIAQgPQAKALASAAQAVgBAAgPQAAgGgDgEQgEgDgHgBIgOgCQgPgDgIgGQgJgJAAgPQAAgRAMgJQALgKASAAQAZAAAOANIgOAQQgJgJgQAAQgIAAgFAEQgFAFAAAHQAAAFAEADQAEAEAHABIANACQAPACAIAHQAKAIAAARQAAARgNAKQgNAJgTAAQgcABgQgRg");
	this.shape_42.setTransform(-78.7,22.9);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#004792").s().p("AgfAxQgNgLAAgTIAAhPIAYAAIAABOQAAAKAGAGQAFAGAJAAQAKAAAFgGQAGgGAAgKIAAhOIAYAAIAABPQAAATgNALQgNAMgTAAQgSAAgNgMg");
	this.shape_43.setTransform(-89.1,22.9);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#004792").s().p("AATA8IgXgwIgRAAIAAAwIgYAAIAAh3IAvAAQARAAAMALQAKAKAAAQQAAAMgHAIQgGAHgJADIAbA0gAgVgGIAVAAQAIAAAFgFQAEgFAAgGQAAgIgEgEQgFgEgIgBIgVAAg");
	this.shape_44.setTransform(-99.9,22.9);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#004792").s().p("AgLA8IAAhjIggAAIAAgUIBXAAIAAAUIggAAIAABjg");
	this.shape_45.setTransform(-110.7,22.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.FR3copy, new cjs.Rectangle(-117.6,13.3,137.9,101), null);


(lib.FR1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#004792").s().p("AAmANQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgVQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAXAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAVQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAgAgKANQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgVQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAVAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAVQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAgAg7ANQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgVQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAWAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAVQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape.setTransform(94.1,68.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#004792").s().p("AgoBBQgBgBAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAh9QAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIBRAAQABAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAUQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIg2AAIgBABIAAAaQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAABAAIAtAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAABIAAATQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgtAAIgBABIAAAbIABABIA2AAQABAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAAAVQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBABg");
	this.shape_1.setTransform(81.6,63.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#004792").s().p("AgpBBQgBgBAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgWIAAgBIA3hPIAAAAIgzAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgVQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIBSAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAVIAAACIg3BOIA2AAQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAAAWQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAABg");
	this.shape_2.setTransform(70.9,63.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#004792").s().p("AgLBBQAAgBgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAh9QAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIAXAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAB9QAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAABg");
	this.shape_3.setTransform(63.1,63.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#004792").s().p("AgOBBQgHgBgHgCIgLgGIgKgHQAAAAAAgBQgBAAAAAAQAAgBABAAQAAgBAAAAIAPgRQAAAAAAAAQAAgBABAAQAAAAAAABQABAAAAAAQAHAFAIAEQAJAEAJAAQALAAAFgEQAFgEAAgHQAAgGgEgDQgEgEgMgBIgFgBQgUgDgLgJQgKgJAAgRQAAgJADgHQADgIAGgFQAGgFAJgDQAIgDAJAAQANAAAMAEQALAEAIAGQABAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABIgMARQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQgIgFgHgDQgIgCgIAAQgHAAgEAEQgFAEAAAGQAAAFAFAEQAEAEAKABIAHABQAUADALAJQAKAJAAARQAAAJgDAHQgEAIgGAFQgGAGgKADQgJADgNAAQgHAAgHgCg");
	this.shape_4.setTransform(54.7,63.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#004792").s().p("AgOBBQgHgBgHgCIgLgGIgKgHQAAAAAAgBQgBAAAAAAQAAgBABAAQAAgBAAAAIAPgRQAAAAAAAAQAAgBABAAQAAAAAAABQABAAAAAAQAHAFAIAEQAJAEAJAAQALAAAFgEQAFgEAAgHQAAgGgEgDQgEgEgMgBIgFgBQgUgDgLgJQgKgJAAgRQAAgJADgHQADgIAGgFQAGgFAJgDQAIgDAJAAQANAAAMAEQALAEAIAGQABAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABIgMARQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQgIgFgHgDQgIgCgIAAQgHAAgEAEQgFAEAAAGQAAAFAFAEQAEAEAKABIAHABQAUADALAJQAKAJAAARQAAAJgDAHQgEAIgGAFQgGAGgKADQgJADgNAAQgHAAgHgCg");
	this.shape_5.setTransform(39,63.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#004792").s().p("AgLBBQAAgBgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAh9QAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIAXAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAB9QAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBABg");
	this.shape_6.setTransform(30.8,63.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#004792").s().p("AAYBBQAAgBgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgyQAAAAAAgBQAAAAAAAAQAAAAgBAAQAAgBAAAAIgpAAQAAAAAAABQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAyQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBABIgYAAQAAgBgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAh9QAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIAYAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAwQAAABAAAAQAAAAAAABQAAAAABAAQAAAAAAAAIApAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIAAgwQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIAYAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAB9QAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBABg");
	this.shape_7.setTransform(21.9,63.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#004792").s().p("AgLBBQAAgBgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAhkQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAgBAAIghAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgVQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIBfAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAVQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIghAAQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAABIAABkQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBABg");
	this.shape_8.setTransform(10.4,63.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#004792").s().p("AgLBAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAhjQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAgBAAIghAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIAAgWQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAgBIBfAAQAAABABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAWQAAAAAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIghAAQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAABIAABjQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_9.setTransform(174.6,37.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#004792").s().p("AgaA7QgMgIgFgQIgBgGIgCgHIAAgJIAAgNIAAgMIAAgJIACgHIABgGQAFgQAMgIQAMgIAQAAQARAAALAIQAMAIAFANQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAIgUAKQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgDgGgFgFQgEgEgJAAQgGAAgFAEQgFAEgCAGIgBAEIAAAFIgBAIIAAAKIAAAMIABAHIAAAFIABAEQACAHAFADQAFAEAGAAQAJAAAEgEQAFgEADgGQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABABIAUAJQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQgFAOgMAHQgLAIgRAAQgQAAgMgIg");
	this.shape_10.setTransform(164.3,37.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#004792").s().p("AgoBAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAh8QAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAABgBIBRAAQABABAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAUQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIg2AAIgBABIAAAZQAAAAAAABQAAAAAAAAQAAAAAAAAQABABAAAAIAtAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIAAASQAAABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgtAAIgBACIAAAbIABABIA2AAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAUQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_11.setTransform(153.6,37.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#004792").s().p("AgaA9QgKgFgEgHQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAAAABgBIASgNQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAAAABIAHAFQAEACAFAAQAIAAAFgGQAFgGAAgLIAAhRQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABgBIAYAAQABABAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAABQQAAAYgMAMQgNANgVAAQgMAAgKgFg");
	this.shape_12.setTransform(142.7,37.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#004792").s().p("AgdA7QgMgIgFgPIgCgHIgBgHIgBgJIAAgNIAAgLIABgJIABgIIACgGQAFgQAMgIQANgIAQAAQARAAAMAIQANAIAFAQIACAGIABAIIAAAJIABALIgBANIAAAJIgBAHIgCAHQgFAPgNAIQgMAIgRAAQgQAAgNgIgAgMglQgFAEgCAGIgBAEIgBAGIAAAHIgBAKIABALIAAAIIABAFIABAEQACAHAFADQAFAEAHAAQAIAAAFgEQAFgDACgHIABgEIABgFIAAgIIAAgLIAAgKIAAgHIgBgGIgBgEQgCgGgFgEQgFgEgIAAQgHAAgFAEg");
	this.shape_13.setTransform(132.6,37.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#004792").s().p("AAWBAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgWguIgRAAIgBAAIAAAuQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgYAAQAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAgBIAAh8QAAAAAAgBQABAAAAAAQAAAAAAAAQABAAAAgBIAzAAQAJABAIACQAJADAFAFQAGAGADAHQADAIAAAIQAAANgGAJQgGAJgLAEIAaAzIAAACIgBAAgAgVgmIAAAdIABABIAWAAQAIABAFgFQAEgEAAgIQAAgHgEgEQgFgFgIABIgWAAIgBABg");
	this.shape_14.setTransform(121.1,37.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#004792").s().p("AgtBAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAh8QAAAAABgBQAAAAAAAAQAAAAABAAQAAAAABgBIAwAAQALABAIACQAIAEAHAFQAGAGADAHQACAHAAAKQAAAJgCAHQgEAHgFAGQgHAFgIAEQgIACgLAAIgVAAIgCABIAAArQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAgAgUgmIAAAgIACABIAUAAQAJAAAEgEQAGgFgBgIQABgIgGgFQgEgFgJABIgUAAIgCABg");
	this.shape_15.setTransform(109.6,37.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#004792").s().p("AAgBAQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIgHgWIgtAAIgHAWQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgZAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAth8QAAAAAAgBQABAAAAAAQAAAAABAAQAAAAAAgBIAXAAQABABAAAAQABAAAAAAQAAAAABAAQAAABAAAAIArB8QABABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAgAAPAQIgPgsIAAAAIgOAsIAdAAg");
	this.shape_16.setTransform(92.9,37.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#004792").s().p("AguBAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAh8QAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABgBIAvAAQARAAALAIQAMAGAEAPIACAGIABAHIAAAKIABAMIgBAOIAAAJIgBAHIgCAFQgEAPgMAIQgLAGgRAAgAgUglIAABLIABACIAOAAQAJgBAGgDQAGgCACgJIABgDIABgFIAAgHIAAgKIAAgJIAAgIIgBgEIgBgEQgCgHgGgEQgGgDgJAAIgOAAQAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAABg");
	this.shape_17.setTransform(76.6,37.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#004792").s().p("AgoBAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAh8QAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAABgBIBRAAQABABAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAUQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIg2AAIgBABIAAAZQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABABAAIAtAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIAAASQAAABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgtAAIgBACIAAAbIABABIA2AAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAUQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_18.setTransform(65.3,37.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#004792").s().p("AgpBAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAh8QAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABgBIAYAAQAAABABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAABkIABACIA4AAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAUQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_19.setTransform(54.9,37.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#004792").s().p("AAYBAQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAIgdg3IgQAVIAAAhQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgYAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAh8QAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABgBIAYAAQAAABABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAA4IApg4QABAAAAgBQABAAAAAAQAAAAABAAQAAAAABgBIAbAAIABABIAAACIgnAxIArBKQAAABAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_20.setTransform(43.6,37.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#004792").s().p("AgaA7QgMgIgFgQIgBgGIgCgHIAAgJIAAgNIAAgMIAAgJIACgHIABgGQAFgQAMgIQAMgIAQAAQARAAALAIQAMAIAFANQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAIgUAKQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgDgGgFgFQgEgEgJAAQgGAAgFAEQgFAEgCAGIgBAEIAAAFIgBAIIAAAKIAAAMIABAHIAAAFIABAEQACAHAFADQAFAEAGAAQAJAAAEgEQAFgEADgGQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABABIAUAJQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQgFAOgMAHQgLAIgRAAQgQAAgMgIg");
	this.shape_21.setTransform(31.7,37.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#004792").s().p("AAgBAQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIgHgWIgtAAIgHAWQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgZAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAth8QAAAAAAgBQABAAAAAAQAAAAABAAQAAAAAAgBIAXAAQABABAAAAQABAAAAAAQAAAAABAAQAAABAAAAIArB8QABABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAgAAPAQIgPgsIAAAAIgOAsIAdAAg");
	this.shape_22.setTransform(20.6,37.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#004792").s().p("AgLBAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAhjQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAgBAAIghAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIAAgWQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAgBIBfAAQAAABABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAWQAAAAAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIghAAQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAABIAABjQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_23.setTransform(10.4,37.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#004792").s().p("AAWBBQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAgBIgWgvIgRAAIgBABIAAAuQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgYAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAgBIAAh8QAAAAAAgBQABAAAAAAQAAAAAAAAQABgBAAAAIAzAAQAJAAAIADQAJADAFAGQAGAFADAHQADAHAAAKQAAAMgGAJQgGAIgLAGIAaAyIAAACIgBABgAgVgnIAAAeIABACIAWAAQAIAAAFgFQAEgEAAgHQAAgIgEgEQgFgEgIAAIgWAAIgBAAg");
	this.shape_24.setTransform(177.7,11.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#004792").s().p("AgoBBQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAh8QAAAAAAgBQAAAAAAAAQAAAAABAAQAAgBABAAIBRAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAAVQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIg2AAIgBAAIAAAaQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAABAAIAtAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIAAAUQAAAAAAAAQAAABgBAAQAAAAAAAAQAAABgBAAIgtAAIgBABIAAAbIABABIA2AAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAUQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_25.setTransform(166.3,11.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#004792").s().p("AgKBBQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAgBgBIgph7QAAgBAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIAZAAQAAAAABABQAAAAABAAQAAAAAAAAQAAABAAAAIAZBUIABAAIAZhUQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBAAAAIAZAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAgBABIgpB7QAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_26.setTransform(155.1,11.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#004792").s().p("AgoBBQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAh8QAAAAAAgBQAAAAAAAAQABAAAAAAQAAgBABAAIBRAAQABAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAAAVQAAAAAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIg2AAIgBAAIAAAaQAAAAAAABQAAAAAAAAQAAAAAAAAQABAAAAAAIAtAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIAAAUQAAAAAAAAQAAABgBAAQAAAAAAAAQAAABgBAAIgtAAIgBABIAAAbIABABIA2AAQABAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAUQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_27.setTransform(144.3,11.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#004792").s().p("AAZBBQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAgBgBIgthQIgBAAIAABQQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgVAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAgBIAAh8QAAAAAAgBQABAAAAAAQAAAAAAAAQABgBAAAAIAXAAQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAIAtBRIABAAIAAhRQAAAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAIAWAAQAAAAABABQAAAAAAAAQAAAAABAAQAAABAAAAIAAB8QAAABAAAAQgBABAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_28.setTransform(132.6,11.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#004792").s().p("AgoBBQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAh8QAAAAAAgBQAAAAAAAAQABAAAAAAQAAgBABAAIBRAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAAVQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIg2AAIgBAAIAAAaQAAAAAAABQAAAAAAAAQAAAAAAAAQABAAAAAAIAtAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIAAAUQAAAAAAAAQAAABgBAAQAAAAAAAAQAAABgBAAIgtAAIgBABIAAAbIABABIA2AAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAUQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_29.setTransform(116.8,11.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#004792").s().p("AgKBBQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAgBgBIgph7QAAgBAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIAZAAQAAAAABABQAAAAABAAQAAAAAAAAQAAABAAAAIAZBUIABAAIAZhUQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBAAAAIAZAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAgBABIgpB7QAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_30.setTransform(105.6,11.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#004792").s().p("AgGAUQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAgjQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIANAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAjQAAAAgBABQAAAAAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_31.setTransform(97.8,7.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#004792").s().p("AgTA/QgJgEgHgGQgGgGgEgKQgDgJAAgMIAAhPQAAAAAAgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAYAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAABPQAAAMAGAGQAGAHAJAAQAJAAAHgHQAFgGAAgMIAAhPQAAAAABgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAYAAQABAAAAABQABAAAAAAQAAAAAAAAQABABAAAAIAABPQgBAMgEAJQgDAKgGAGQgHAGgJAEQgKADgKAAQgKAAgJgDg");
	this.shape_32.setTransform(89.6,11.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#004792").s().p("AgdA7QgMgIgFgPIgCgHIgBgHIgBgJIAAgNIAAgLIABgJIABgIIACgGQAFgQAMgIQANgIAQAAQARAAAMAIQANAIAFAQIACAGIABAIIAAAJIABALIgBANIAAAJIgBAHIgCAHQgFAPgNAIQgMAIgRAAQgQAAgNgIgAgMglQgFAEgCAGIgBAEIgBAGIAAAHIgBAKIABALIAAAIIABAFIABAEQACAHAFADQAFAEAHAAQAIAAAFgEQAFgDACgHIABgEIABgFIAAgIIAAgLIAAgKIAAgHIgBgGIgBgEQgCgGgFgEQgFgEgIAAQgHAAgFAEg");
	this.shape_33.setTransform(77.5,11.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#004792").s().p("AgLBBQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAgBIAAgxIgmhLQAAAAAAgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAZAAQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAIAWAwIABAAIAXgwQAAAAABgBQAAAAAAAAQAAAAABAAQAAgBABAAIAYAAIABABIAAABIgmBLIAAAxQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_34.setTransform(66.4,11.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#004792").s().p("AAZBBQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAgBgBIgthQIgBAAIAABQQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgVAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAgBIAAh8QAAAAAAgBQABAAAAAAQAAAAAAAAQABgBAAAAIAXAAQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAIAtBRIABAAIAAhRQAAAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAIAWAAQAAAAABABQAAAAAAAAQAAAAABAAQAAABAAAAIAAB8QAAABAAAAQgBABAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_35.setTransform(50.9,11.7);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#004792").s().p("AgoBBQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAh8QAAAAAAgBQAAAAAAAAQABAAAAAAQAAgBABAAIBRAAQABAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAAAVQAAAAAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIg2AAIgBAAIAAAaQAAAAAAABQAAAAAAAAQAAAAAAAAQABAAAAAAIAtAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIAAAUQAAAAAAAAQAAABgBAAQAAAAAAAAQAAABgBAAIgtAAIgBABIAAAbIABABIA2AAQABAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAUQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_36.setTransform(39.6,11.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#004792").s().p("AAYBBQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgxQAAAAAAgBQAAAAAAAAQAAAAgBAAQAAAAAAAAIgpAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAxQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgYAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAh8QAAAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIAYAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAAxQAAAAAAAAQAAAAAAABQAAAAABAAQAAAAAAAAIApAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAIAAgxQAAAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIAYAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAB8QAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_37.setTransform(27.8,11.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#004792").s().p("AAZBBQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIgXhPIAAAAIgWBPQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgTAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAgBIghh8QAAAAAAgBQAAAAAAAAQABAAAAAAQAAgBABAAIAYAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIATBRIAAAAIAWhRQAAAAABgBQAAAAAAAAQAAAAABAAQAAgBABAAIAPAAQABAAAAABQABAAAAAAQAAAAAAAAQABABAAAAIAWBRIABAAIAShRQAAAAAAgBQAAAAAAAAQABAAAAAAQAAgBABAAIAYAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIghB8QAAABgBAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_38.setTransform(13.3,11.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.FR1copy, new cjs.Rectangle(3.1,0,187.4,78.4), null);


(lib.button_hoover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// GET STARTED
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgbAnIAAhNIAbAAQANAAAHAHQAGAGABAJIABAQIgBARQgBAJgGAGQgHAHgNAAgAgPAdIAPAAQAHAAAFgGQACgDABgGIABgOIgBgNQgBgGgCgDQgFgFgHAAIgPAAg");
	this.shape.setTransform(83.5,12.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAnIAAhNIAxAAIAAALIglAAIAAAWIAfAAIAAAKIgfAAIAAAYIAlAAIAAAKg");
	this.shape_1.setTransform(76.6,12.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgFAnIAAhCIgWAAIAAgLIA2AAIAAALIgVAAIAABCg");
	this.shape_2.setTransform(70,12.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAPAnIgQghIgPAAIAAAhIgMAAIAAhNIAeAAQALAAAHAGQAGAHAAAKQAAAIgEAGQgFAEgGACIASAigAgQgDIARAAQAGAAAEgDQADgDAAgGQAAgGgDgDQgEgDgGAAIgRAAg");
	this.shape_3.setTransform(63.6,12.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAUAnIgEgPIgfAAIgFAPIgNAAIAdhNIAJAAIAdBNgAAMANIgMghIgLAhIAXAAg");
	this.shape_4.setTransform(56.3,12.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgFAnIAAhCIgVAAIAAgLIA2AAIAAALIgXAAIAABCg");
	this.shape_5.setTransform(49.8,12.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgbAeIAIgIQAHAHAMAAQAIAAAEgDQAEgDAAgGQAAgFgDgDQgDgCgFgBIgJgCQgJgBgGgEQgFgFAAgKQAAgKAHgGQAHgHALAAQAPAAAJAJIgHAIQgHgGgKAAQgGAAgEADQgEADAAAGQAAAEADADQADADAGABIAIABQAKABAFAEQAGAFAAALQAAALgIAGQgIAGgMAAQgRAAgKgKg");
	this.shape_6.setTransform(43.4,12.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgFAnIAAhCIgVAAIAAgLIA1AAIAAALIgVAAIAABCg");
	this.shape_7.setTransform(34.6,12.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgYAnIAAhNIAxAAIAAALIglAAIAAAWIAfAAIAAAKIgfAAIAAAYIAlAAIAAAKg");
	this.shape_8.setTransform(28.4,12.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgUAgQgFgGgBgHIgBgTQAAgNABgEQABgIAFgFQAJgJALAAQAMAAAHAHQAIAHABALIgMAAQgDgOgNAAQgGAAgFAFQgDADgBAFIgBAPIABARQABAEADAEQAFAEAGAAQAIAAAFgFQAEgFAAgIIAAgEIgRAAIAAgJIAcAAIAAALQAAAPgHAHQgIAJgNAAQgLAAgJgIg");
	this.shape_9.setTransform(21.4,12.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Layer 1
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0471AF").s().p("AoRCCIAAkDIQjAAIAAEDg");
	this.shape_10.setTransform(53,13);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#004990").s().p("AoRCCIAAkDIQjAAIAAEDg");
	this.shape_11.setTransform(53,13);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10}]}).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_10}]},1).to({state:[]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.4,0,106.5,26);


(lib.button_cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(193,220,235,0)").ss(0.1,1,1).p("A4q0gMAxVAAAMAAAApBMgxVAAAg");
	this.shape.setTransform(157.9,131.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00CC00").s().p("A4qUhMAAAgpBMAxVAAAMAAAApBg");
	this.shape_1.setTransform(157.9,131.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Tween7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.button_hoover();
	this.instance.parent = this;
	this.instance.setTransform(-84,0,1,1,0,0,0,53,13);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.button_hoover(), 3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(193,220,235,0)").ss(0.1,1,1).p("AoFCAIgbAAIAAj/IAbAAAIfh/IACAAIAAD/IgCAA");
	this.shape.setTransform(83,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-137.5,-13.5,276,27.5);


(lib.start_with_lowes_white = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.start_w_lowes_stack("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(116.8,21.8,0.867,0.867,0,0,0,139.6,25.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.start_with_lowes_white, new cjs.Rectangle(-4.3,0.1,242,43.3), null);


// stage content:
(lib.projmgmt_300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.button_cta.addEventListener("click", fl_ClickToGoToWebPage);
		function fl_ClickToGoToWebPage() {
			window.open("https://www.lowes.com/GetInstalled", "_blank");
		}
		
		
		
		if ( ! this.alreadyExecuted) {
		  this.alreadyExecuted = true;
		  this.loopNumber = 0;
		} else {
		  this.loopNumber++;
		  if (this.loopNumber == 1) {
		    this.stop();
		  }
		}
	}
	this.frame_254 = function() {
		this.button_cta.addEventListener("click", fl_ClickToGoToWebPage);
		function fl_ClickToGoToWebPage() {
			window.open("https://www.lowes.com/GetInstalled", "_blank");
		}
		
		
		
		
		if ( ! this.alreadyExecuted) {
		  this.alreadyExecuted = true;
		  this.loopNumber = 0;
		} else {
		  this.loopNumber++;
		  if (this.loopNumber == 1) {
		    this.stop();
		  }
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(254).call(this.frame_254).wait(1));

	// Clicktag
	this.button_cta = new lib.button_cta();
	this.button_cta.name = "button_cta";
	this.button_cta.parent = this;
	this.button_cta.setTransform(151.3,124.6,1,1,0,0,0,157.9,131.2);
	new cjs.ButtonHelper(this.button_cta, 0, 1, 2, false, new lib.button_cta(), 3);

	this.timeline.addTween(cjs.Tween.get(this.button_cta).wait(255));

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#04649A").ss(1,1,1).p("A3ZzhMAuzAAAQAAACACAAMAAAAm/QgCAAAAACMguzAAAQAAgCgCAAMAAAgm/QACAAAAgCg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(255));

	// F1 copy
	this.instance = new lib.FR1copy();
	this.instance.parent = this;
	this.instance.setTransform(-101.2,171.3,1,1,0,0,0,95.8,46.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:2.8,alpha:0.488},12).to({x:106.7,alpha:1},4).to({x:121.8},66).to({_off:true},1).wait(172));

	// loweslogo
	this.instance_1 = new lib.Tween1("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(257.6,27.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({startPosition:0},78).to({alpha:0},4).to({_off:true},1).wait(172));

	// mtapeMASK (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("A3aThMAAAgnBMAu1AAAMAAAAnBg");
	var mask_graphics_82 = new cjs.Graphics().p("A3aThMAAAgnBMAu1AAAMAAAAnBg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:149.9,y:125.1}).wait(82).to({graphics:mask_graphics_82,x:149.9,y:125.1}).wait(173));

	// tape
	this.instance_2 = new lib.mtape();
	this.instance_2.parent = this;
	this.instance_2.setTransform(5,22,0.152,0.152);

	this.instance_3 = new lib.Tween5("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(147,109.5);

	var maskedShapeInstanceList = [this.instance_2,this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2}]}).to({state:[{t:this.instance_3}]},78).to({state:[{t:this.instance_3}]},4).to({state:[]},1).wait(172));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(78).to({startPosition:0},0).to({alpha:0},4).to({_off:true},1).wait(172));

	// button
	this.instance_4 = new lib.Tween7("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(317.3,223);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(214).to({_off:false},0).to({alpha:1},8).to({startPosition:0},32).wait(1));

	// F3 copy
	this.instance_5 = new lib.FR3copy();
	this.instance_5.parent = this;
	this.instance_5.setTransform(211.2,175.8,1,1,0,0,0,81.6,49.9);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(163).to({_off:false},0).to({alpha:0.129},1).to({y:175.5,alpha:1},7).wait(84));

	// loweslogo
	this.instance_6 = new lib.Tween4("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(257.5,28);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(154).to({_off:false},0).to({alpha:1},5).to({startPosition:0},95).wait(1));

	// BobMASK (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_154 = new cjs.Graphics().p("A3aThMAAAgnBMAu1AAAMAAAAnBg");
	var mask_1_graphics_254 = new cjs.Graphics().p("A3aThMAAAgnBMAu1AAAMAAAAnBg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(154).to({graphics:mask_1_graphics_154,x:149.9,y:125.1}).wait(100).to({graphics:mask_1_graphics_254,x:149.9,y:125.1}).wait(1));

	// white gradient
	this.instance_7 = new lib.white_gradient_1("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(116.7,122.7,0.855,1.261,90,0,0,149,104.7);
	this.instance_7.alpha = 0.762;

	this.instance_8 = new lib.white_gradient_1("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(116.7,122.7,0.855,1.261,90,0,0,149,104.7);
	this.instance_8.alpha = 0.762;

	this.instance_9 = new lib.white_gradient_1("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(134,122.7,0.855,1.261,90,0,0,149,104.7);
	this.instance_9.alpha = 0.762;

	this.instance_10 = new lib.white_gradient_1("synched",0);
	this.instance_10.parent = this;
	this.instance_10.setTransform(134,122.7,0.855,1.261,90,0,0,149,104.7);
	this.instance_10.alpha = 0.762;

	var maskedShapeInstanceList = [this.instance_7,this.instance_8,this.instance_9,this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_10},{t:this.instance_9},{t:this.instance_8},{t:this.instance_7}]},154).to({state:[{t:this.instance_10},{t:this.instance_9},{t:this.instance_8},{t:this.instance_7}]},100).wait(1));

	// BOB
	this.instance_11 = new lib.bob();
	this.instance_11.parent = this;
	this.instance_11.setTransform(0,0,0.229,0.229);

	this.instance_12 = new lib.Tween6("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(178.5,159.5);
	this.instance_12.alpha = 0;

	var maskedShapeInstanceList = [this.instance_11,this.instance_12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_12,p:{alpha:0}},{t:this.instance_11}]},154).to({state:[{t:this.instance_12,p:{alpha:1}},{t:this.instance_11}]},4).to({state:[{t:this.instance_12,p:{alpha:1}},{t:this.instance_11}]},96).wait(1));

	// start with lowes
	this.instance_13 = new lib.start_with_lowes_white();
	this.instance_13.parent = this;
	this.instance_13.setTransform(422.5,120.2,1,1,0,0,0,116.6,21.7);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(79).to({_off:false},0).wait(1).to({regX:118.2,regY:21.4,x:390.3,y:119.9,alpha:0.042},0).wait(1).to({x:357.3,alpha:0.083},0).wait(1).to({x:325.3,alpha:0.125},0).wait(1).to({x:294,alpha:0.167},0).wait(1).to({x:263.6,alpha:0.208},0).wait(1).to({x:234,alpha:0.25},0).wait(1).to({x:205.2,alpha:0.292},0).wait(1).to({x:177.2,alpha:0.333},0).wait(1).to({x:150.1,alpha:0.375},0).wait(1).to({alpha:0.417},0).wait(1).to({alpha:0.458},0).wait(1).to({alpha:0.5},0).wait(1).to({alpha:0.542},0).wait(1).to({alpha:0.583},0).wait(1).to({alpha:0.625},0).wait(1).to({alpha:0.667},0).wait(1).to({alpha:0.708},0).wait(1).to({alpha:0.75},0).wait(1).to({alpha:0.792},0).wait(1).to({alpha:0.833},0).wait(1).to({alpha:0.875},0).wait(1).to({alpha:0.917},0).wait(1).to({alpha:0.958},0).wait(1).to({alpha:1},0).wait(54).to({_off:true},1).wait(97));

	// background
	this.instance_14 = new lib.Tween3("synched",0);
	this.instance_14.parent = this;
	this.instance_14.setTransform(150.4,125.6,0.96,0.968,0,0,0,0.1,0.2);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(78).to({_off:false},0).to({_off:true},80).wait(97));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-43.9,117.4,504.1,264.5);
// library properties:
lib.properties = {
	id: '9A27E2F3A84F463E9869F4B5E2AF43DD',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bob.jpg", id:"bob"},
		{src:"images/L880302pPreview.jpg", id:"L880302pPreview"},
		{src:"images/logo_lowes_blue2_68x148.png", id:"logo_lowes_blue2_68x148"},
		{src:"images/mtape.jpg", id:"mtape"},
		{src:"images/white_gradient.png", id:"white_gradient"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['9A27E2F3A84F463E9869F4B5E2AF43DD'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;